- system/tests/test_utils.py
- system/utils.py
Fixes things like this
```
In [1]: from simtk import unit
In [2]: import pint
In [3]: u = pint.UnitRegistry()
In [4]: val = 5.0 * unit.angstrom
In [5]: u(val.unit.get_symbol())
Out[5]: 1 <Unit('ampere')>
In [6]: u(val.unit.get_name())
Out[6]: 1 <Unit('angstrom')>
```
and provides a better framework for expanding the coverage of the relevant unit test
> Parse SimTK units with get_name instead of get_symbol

- .github/workflows/ci.yaml
- devtools/conda-envs/test_env.yaml
- openff/system/tests/test_interop/test_parmed.py
This PR switches to using a released version of the OpenFF Toolkit. I believe the development version was only being used for https://github.com/openforcefield/openforcefield/pull/711
> Use OpenFF Toolkit 0.7.2

- .github/workflows/ci.yaml
- .github/workflows/integration_tests.yaml
- devtools/conda-envs/intermol_env.yaml
- openff/system/interop/parmed.py
- openff/system/tests/integration_tests/int.py
- openff/system/tests/integration_tests/test_interoperability_pathways.py
- openff/system/tests/utils.py
This adds a very basic and kinda hacky test that demonstrates how InterMol can be used for integration testing. The intent is to build this out for other engines and systems for a fairly dense matrix, similar to some of the tests in `intermol/tests/*/unit_tests/`
> Add Integration tests

- .github/workflows/integration_tests.yaml
- openff/system/components/potentials.py
- openff/system/components/smirnoff.py
- openff/system/components/system.py
- openff/system/exceptions.py
- openff/system/interop/parmed.py
- openff/system/stubs.py
- openff/system/tests/base_test.py
- openff/system/tests/integration_tests/test_interoperability_pathways.py
- openff/system/tests/test_interop/test_parmed.py
- openff/system/tests/utils.py
This PR updates the old ParmEd converter for new components, including building out more core attributes of the `System` class.
> Update ParmEd converter for new components

- openff/system/components/potentials.py
- openff/system/exceptions.py
- openff/system/tests/test_potential.py
- setup.cfg
This PR drops `sympy` as an expression validator until an appropriate solution to #56 can be found. It also makes some small improvements to the tests.
> Drop sympy for expression parsing

- openff/system/tests/test_interop/test_parmed.py
This PR adds in some non-exhaustive tests  of the ParmEd conversion module. It should at least increase the test coverage.
> Add basic ParmEd tests

- openff/system/components/potentials.py
- openff/system/components/smirnoff.py
- openff/system/components/system.py
- openff/system/interop/parmed.py
- openff/system/tests/integration_tests/test_interoperability_pathways.py
- openff/system/tests/test_interop/test_parmed.py
- openff/system/tests/test_potential.py
- openff/system/tests/test_utils.py
- openff/system/utils.py
This PR removes the half-measures of scattered unit implementations until we can arrive at a solution that is more suitable and general for the rest of the OpenFF software stack.
Related #60
> Use implicit units in models

- openff/system/components/smirnoff.py
- openff/system/interop/parmed.py
This PR implements the change in #51 for the current `SMIRNOFFElectrostaticsHandler`, which I neglected to do (probably because of different attribute names).
> Make SMIRNOFFElectrostaticsHandler use str keys

- .github/workflows/ci.yaml
- devtools/conda-envs/intermol_env.yaml
- devtools/conda-envs/test_env.yaml
This PR attempts to add Python 3.8 and 3.9 to CI, now that OpenMM's migration to `conda-forge` has  unblocked much of our dependencies.
> Test on Python 3.8 and 3.9

- openff/system/components/smirnoff.py
- openff/system/components/system.py
- openff/system/exceptions.py
- openff/system/interop/openmm.py
- openff/system/stubs.py
- openff/system/tests/test_interop/test_openmm.py
This PR adds `System.to_openmm` for exporting to `openmm.System`.
I am starting with an approach that does not try to treat each handler similarly and instead hardcodes the addition of each force. This is because, while our view of an internal representation of a parametrized system may be elegantly siloed into separate parameters, external libraries like OpenMM will never structure data in precisely the same way. The hope is that separating out the processing at export from the internal representation will allow for the complexity of this interface to exist, but only exist in one place, a place that is safely controlled and mostly quarantined from the rest of the codebase.
> Add to_openmm

- openff/system/interop/openmm.py
- openff/system/tests/test_interop/test_openmm.py
This PR updates the OpenMM export tests and also fixes setting the nonbonded methods in the `NonbondedForce` when the vdW and Electrostatics cutoff methods in the SMIRNOFF force field are set to `Cutoff` and `PME`, respectively (the default/common case).
When working on #69 I was frustrated by how difficult OpenMM made comparing energies - turns out I was simply disregarding existing functionality in the OpenFF Toolkit. Thanks @j-wags
> Update OpenMM tests and nonbonded methods

- .github/workflows/ci.yaml
- .github/workflows/integration_tests.yaml
This PR drops Python 3.9 from CI, since those environments were falling back to 3.8, and ticks up the minor versions used in integration tests.
> Update Python versions in tests

- openff/system/components/smirnoff.py
- openff/system/interop/openmm.py
- openff/system/stubs.py
- openff/system/tests/files/README.md
- openff/system/tests/files/parsley.offxml
- openff/system/tests/test_interop/test_openmm.py
This PR adds support for improper torsions in SMIRNOFF and the export to OpenMM. Some of this is copied from the corresponding code in the toolkit, but energies are not yet equal.
> Add improper torsions, fix multi-term torsions in OpenMM export

- openff/system/stubs.py
- openff/system/tests/test_interop/test_parmed.py
- openff/system/tests/test_types.py
- openff/system/types.py
- openff/system/utils.py
- setup.cfg
This PR beings to implement some models for `pint.Quantity` wrappers that play well with pydantic models.
> Add unit models

- devtools/conda-envs/intermol_env.yaml
- devtools/conda-envs/test_env.yaml
- openff/system/tests/test_types.py
- openff/system/types.py
- setup.cfg
This PR adds support for `unyt`, at least in the context of parsing `unyt` data into the existing unit models. Internally, the thin wrapper around `pint` and its associated unit registry are unchanged.
I found a minor complication resulting from `unyt.unyt_quantity` being a subclass of `unyt.unyt_array`, which is that `.to_pint()` gives an array-like `pint.Quantity` when you’d expect something float-like. I’m able to hack this without much effort in pint. I don’t expect this to be a major issue, but it will be hard to tell with only unit tests.
```python3
In [32]: val
Out[32]: unyt_quantity(4, 'nm')
In [33]: val.to_pint()
Out[33]: array(4) <Unit('nanometer')>
In [34]: _from_unyt_quantity(val)
Out[34]: 4.0 <Unit('nanometer')>
> Add support for unyt data in unit models

- devtools/conda-envs/test_env.yaml
`mypy` was recently bumped to 0.800, which introduced several changes. This pins to the old version until I can look into the changes.
> Pin mypy to 0.790

- openff/system/components/potentials.py
- openff/system/exceptions.py
- openff/system/tests/test_matrix_representations.py
- openff/system/tests/test_utils.py
- openff/system/tests/utils.py
- openff/system/utils.py
I'm about to try using OpenFF Recharge for handling BCCs, and I'd like that to be an optional dependency while it's still in an early stage. This PR copies the `requires_package` function from the toolkit for that purpose and surely many future uses. It also removes the old JAX checking.
> Add requires_package

- .github/workflows/ci.yaml
- openff/system/tests/test_interop/test_internal_writers.py
- openff/system/utils.py
Python 3.6 has been out of the NEP 29 recommendations for over a year now. It's not causing any problems, but I'd like to remove it before it does. This also runs `pyupgrade --py37-plus`.
> Drop Python 3.6 from CI

- openff/system/interop/openmm.py
- openff/system/tests/energy_tests/gromacs.py
- openff/system/tests/energy_tests/test_energies.py
- openff/system/tests/files/mdp/cutoff_hbonds.mdp
This PR adds constraints to exporters. They are already stored in the internal representation, I just forgot to include them in the exporters when doing the first implementation.
> Add constraints to exporters

- examples/optimize-with-jax.ipynb
- examples/parameter_replacement.ipynb
- examples/smirnoff_argon.ipynb
- examples/smirnoff_ethanol.ipynb
- openff/system/components/potentials.py
- openff/system/components/smirnoff.py
- openff/system/components/system.py
- openff/system/interop/internal/gromacs.py
- openff/system/interop/internal/lammps.py
- openff/system/interop/openmm.py
- openff/system/interop/parmed.py
- openff/system/models.py
- openff/system/tests/energy_tests/report.py
- openff/system/tests/test_potential.py
- openff/system/tests/test_stubs.py
- openff/system/tests/test_types.py
- openff/system/tests/test_typing.py
- openff/system/types.py
This PR attempts a refactor to some components of the `PotentialHandler` objects. Topological locations are now constructed with `ToplogyKey`s and potentials are uniquely  identified with `PotentialKey`s.
An example (this is a parametrized ethanol):
```python3
In [11]: out['Bonds'].slot_map
Out[11]:
{TopologyKey(atom_indices=(0, 1), mult=None): PotentialKey(id='[#6X4:1]-[#6X4:2]', mult=None),
TopologyKey(atom_indices=(0, 3), mult=None): PotentialKey(id='[#6X4:1]-[#1:2]', mult=None),
TopologyKey(atom_indices=(0, 4), mult=None): PotentialKey(id='[#6X4:1]-[#1:2]', mult=None),
TopologyKey(atom_indices=(0, 5), mult=None): PotentialKey(id='[#6X4:1]-[#1:2]', mult=None),
TopologyKey(atom_indices=(1, 2), mult=None): PotentialKey(id='[#6:1]-[#8:2]', mult=None),
TopologyKey(atom_indices=(1, 6), …
```
> Refactor keys in topology/potential mappings

- devtools/conda-envs/test_env.yaml
- openff/system/tests/energy_tests/gromacs.py
- openff/system/tests/energy_tests/test_energies.py
- openff/system/tests/energy_tests/utils.py
- setup.cfg
While experimenting with Foyer, I noticed that Ryckaert-Bellemans torsions were not processed by the GROMACS energy parser. This is because GROMACS reports it in a separate column as other dihedrals. This PR fixes that.
@j-wags contributed significantly to the development of this code
> Report Ryckaert-Bellemans torsions in GROMACS energy driver

- openff/system/components/misc.py
- openff/system/interop/internal/gromacs.py
- openff/system/interop/openmm.py
- openff/system/tests/energy_tests/openmm.py
- openff/system/tests/test_rb_torsions.py
This PR adds a shim for support Ryckaert-Bellemans torsions. If the parameter keys `c0`, `c1`, ..., `c5` are populated in a handler named `RBTorsions`, it should safely export to GROMACS and OpenMM.
Resolves #139
cc: @umesh-timalsina
> Add Ryckaert-Bellemans torsions

- openff/system/components/system.py
- openff/system/interop/external.py
- openff/system/interop/parmed.py
- openff/system/tests/integration_tests/test_interoperability_pathways.py
- openff/system/tests/test_interop/test_parmed.py
- openff/system/tests/test_parmed.py
This PR makes the ParmEd API points private. I forgot to do it in #145.
> Make ParmEd conversion methods private

- docs/energy_tests.md
- openff/system/tests/energy_tests/gromacs.py
- openff/system/tests/energy_tests/lammps.py
- openff/system/tests/energy_tests/openmm.py
- openff/system/tests/energy_tests/report.py
- openff/system/tests/energy_tests/test_energies.py
- openff/system/tests/test_interop/test_internal_writers.py
- openff/system/tests/test_parmed.py
- openff/system/tests/test_rb_torsions.py
This PR adds some rough initial documentation for the energy tests, including some docstrings.
The important points relating to GROMACS are
1. Call `get_gromacs_energies` directly on a `System` object to get single-point energies
2. Call `_run_gmx_energy` on a collection of GROMACS files (prepared here or externally, i.e. via ParmEd) to get single-point energies. `get_gromacs_energies` calls this function, so the behavior should be similar (or able to be made similar).
3. I've hacked together a few `.mdp` files to cover some types of calculations, but these are not exhaustive and a better solution (programmatically generating them?) should replace these in the future. For now, see [this](https://github.com/openforcefield/openff-system/tree/9bca382ba64aede0be9e9138159db51a58f7a7c8/openff/sy …
> Document energy tests

- openff/system/components/system.py
- openff/system/interop/openmm.py
- openff/system/tests/energy_tests/lammps.py
- openff/system/tests/energy_tests/test_energies.py
- openff/system/tests/test_combination.py
This PR updates the `System` class to follow an "outer/inner" data model in which the internals are hidden away in a pseudo-private inner class and an outer model has some API points for getting/setting pieces of the inner model. This is inspired by the [`Molecule`](https://github.com/SimonBoothroyd/strawman/blob/41cbee89b41b33afa49cbaec9ba28ca4ee5d729b/strawman/molecule.py#L145) class in the "strawman."
> Update API with outer/inner data

- openff/system/components/smirnoff.py
The expression for the `SMIRNOFFAngleHandler` was missing the power of two. This PR fixes the expresion and changes the order to more closely match the `SMIRNOFFBondHandler` for consistency (i.e. independent D.O.F - parameter).
> Fix SMIRNOFF angle handler expression

- devtools/conda-envs/minimal_env.yaml
- devtools/conda-envs/test_env.yaml
- openff/system/tests/energy_tests/report.py
- openff/system/tests/energy_tests/test_energies.py
- setup.cfg
Previously, a failing energy test (`energy_report.compare(other_energy_report)`) would only report the first kind of energy that failed a comparison, which led to some headaches in debugging. For example, if all valence energies were off, only one was reported (probably bonds, but not always ordered) and the others were not reported. The output is also significantly more human-readable.
I'm lazy and using a pandas data frame for this, which could be removed in the future if we don't need it for any other uses.
Before:
```
Traceback (most recent call last):
File "/Users/mwt/software/openff-system/energy_report.py", line 24, in <module>
a.compare(
File "/Users/mwt/software/openff-system/openff/system/tests/energy_tests/report.py", line 111, in compare
raise EnergyError( …
```
> Report all failures in energy tests

- openff/system/components/smirnoff.py
- openff/system/stubs.py
- openff/system/tests/test_matrix_representations.py
- openff/system/tests/test_potential.py
This is a follow-on to #173. The idea is that the monkey-patched  `SMIRNOFFPotentialHandler.create_potential` methods should just be `.from_toolkit` class methods. It wasn't until somebody else read this code that it was noticed I monkey-patched within the same package. Oof!
This should make porting to the toolkit simpler.
> Make SMIRNOFFPotentialHandler.from_toolkit class methods

- devtools/conda-envs/test_env.yaml
- openff/system/exceptions.py
- openff/system/tests/energy_tests/gromacs.py
Yesterday, we ran into some peculiar behavior with the code that parses energy files. This PR drops the call to `gmx energy`, which turns the binary `.edr` files into human-readable `.xvg` files, and uses `panedr` to directly parse the binaries. This picks up a free win by skipping the shell call that handles the conversion.
A better solution may involve keeping both code paths active, but using `panedr` output as a reference. I trust it more than my ability  (and patience) to write perfect file parsers.
Thanks to @justinGilmer for the suggestion.
> Use panedr to parse GROMACS energy files

- openff/system/components/mdtraj.py
- openff/system/components/system.py
- openff/system/tests/test_system.py
This PR fixes creating an OpenFF system object using the `from_smirnoff` class method with a base OpenFF `Topology` object and not an `OFFBioTop`. Previously the existing topology was passed as the `mdtraj` arg, rather than the `other` kwarg.
The PR further adds a workaround to https://github.com/openforcefield/openff-toolkit/issues/946 as OpenFF topologies cannot currently be instantiated from `other`.
> Fix from SMIRNOFF used with base OFF topology

- devtools/conda-envs/minimal_env.yaml
- devtools/conda-envs/test_env.yaml
- docs/index.md
- docs/installation.md
This PR adds long-overdue installation docs. The docs probably don't render right now, please refer only do the Markdown source.
@umesh-timalsina @justinGilmer I wonder if anything else stuck out to you as pain points when you were installing development builds recently? I wrote up the major sore points that came to mind personally - please let me know what I may be missing.
> Add installation docs

- .github/workflows/ci_minimal.yaml
- .github/workflows/cron.yaml
macOS jobs are slow and shared across the organization (limit 5 concurrently across all projects). Given that the differences tend to be small for pure Python packages and that I develop on macOS, and Linux builds are quicker and normally have no queue, it doesn't make much sense to stall progress by waiting on macOS jobs to finish. This also adds nightly tests, which do include macOS builds.
> Add cron job, turn off macOS jobs in CI

- openff/system/components/system.py
- openff/system/drivers/openmm.py
- openff/system/interop/openmm.py
- openff/system/tests/interop/test_external.py
- openff/system/tests/interop/test_openmm.py
This takes https://github.com/openforcefield/openff-toolkit/pull/920 and tries to implement it here.
This is the script I'm currently using to set a trace:
```python3
from openff.toolkit.topology import Molecule
from openff.system.stubs import ForceField
mol = Molecule.from_smiles("ClC#CCl")
mol.name = "HPER"
mol.generate_conformers(n_conformers=1)
parsley = ForceField("openff_unconstrained-1.0.0.offxml")
out = parsley.create_openff_system(topology=mol.to_topology())
out.box = [4, 4, 4]
out.positions = mol.conformers[0]
out['Electrostatics'].method='pme'
out.to_gro("out.gro", writer="internal")
out.to_top("out.top", writer="internal")
from openff.system.drivers.gromacs import _run_gmx_energy, _write_mdp_file
from openff.system.drivers.openmm import get_openmm_energies …
```
> Split NonbondedForce in to_openmm

- .github/workflows/ci.yaml
- .github/workflows/ci_minimal.yaml
- devtools/conda-envs/minimal_env.yaml
- devtools/conda-envs/test_env.yaml
- docs/installation.md
OpenFF Units is now on `conda-forge`, so I can remove the  hacks I put in. And also update the installation docs.
> MAINT: Update environments/docs for openff-units conda package

- openff/system/components/smirnoff.py
- openff/system/components/system.py
- openff/system/exceptions.py
- openff/system/tests/components/test_smirnoff.py
This PR is a prerequisite for finishing #200.
I bet there's a more elegant way to to this - I had a difficult time figuring out how to use Pydantic features to validate something that's not stored in the model.
> Let potential handlers specify allowed parameter handlers

- examples/SMIRNOFF_simulation.ipynb
- examples/smirnoff_argon.ipynb
- examples/smirnoff_ethanol.ipynb
- openff/system/components/smirnoff.py
- openff/system/models.py
- openff/system/tests/components/test_smirnoff.py
This PR adds an optional field to `PotentialKey` for storing the handler that a key is associated with. This seems somewhat trivial for valence parameters, i.e. a potential key between two atoms _stored in_ a `SMIRNOFFBondHandler` is obviously associated with a `BondHandler` parameter handler. It's less obvious, however, for electrostatics models (and likely some more complicated virtual site treatments) in which multiple handlers can apply to the same "slot," i.e. multiple electrostatics parameter handlers can apply to the same atom. This is needed for/a part of #200. This also sets the stage for more complex relationships between parameters and potentials.
I'm currently storing the new field as a string, this may need to change in the future.
> Add PotentialKey.associated_handler

- openff/system/components/smirnoff.py
- openff/system/components/system.py
- openff/system/interop/openmm.py
- openff/system/interop/parmed.py
- openff/system/tests/components/test_smirnoff.py
- openff/system/tests/interop/test_openmm.py
#200 make it more obvious that my earlier approach to handling constraints was inelegant. This PR splits off constraint handling into its own potential handler. The ugliness here is that the constraint handler depends on both a constraint handler from the toolkit and also a bond handler. Within the current SMIRNOFF spec, this is unavoidable, since constraints can be defined without also specifying their distance in the scope of the constraint handler.
> Fix constraints

- .github/workflows/ci.yaml
- devtools/conda-envs/test_env.yaml
OpenFF Recharge v0.0.1 is now on `conda-forge` (and has been for quite some time, I think)
> Test against released version of OpenFF Recharge

- openff/interchange/components/interchange.py
- openff/interchange/components/smirnoff.py
- openff/interchange/exceptions.py
- openff/interchange/tests/components/test_interchange.py
- openff/interchange/tests/components/test_smirnoff.py
This beefs up error handling in some cases of unsupported SMIRNOFF force field contents, namely bond order interpolation (bonds and torsions) and virtual sites.
> Catch more cases of unsupported SMIRNOFF force fields

- .pre-commit-config.yaml
I found this nice hook that enforces debug code, i.e. `import ipdb; ipdb.set_trace()` is not committed. I do this a lot, and automating away the fix seems like a good idea.
> Add debug-statements hook

- .pre-commit-config.yaml
- openff/interchange/components/foyer.py
- openff/interchange/components/potentials.py
- openff/interchange/components/smirnoff.py
- openff/interchange/types.py
- pyproject.toml
- setup.cfg
This PR adopts [`interrogate`](https://github.com/econchick/interrogate) by means of a pre-commit hook. It's  a tool that reports docstring coverage.
I set the threshold for passing to an abysmally low 45% and added just enough docstrings to cross that threshold. This should be raised in the future; for now it may serve as a rough check for if a PR adds a large number of docstring-less functions.
> Adopt interrogate

- openff/interchange/drivers/gromacs.py
We realized some of the differences in our energy tests are due to differences in precision of the positions defined in the gromacs `.gro` file, but that variable could not be changed from the `get_gromacs_energies`. This PR added a `decimal` flag for the `get_gromacs_energies` to address that issue. Related to #182
> Add gro decimal precision for `get_gromacs_energies`

- openff/interchange/tests/components/test_smirnoff.py
- openff/interchange/tests/integration_tests/test_toolkit.py
- openff/interchange/tests/utils.py
This PR includes two small fixes:
* One molecule (DrugBank_2148, which appears to be https://pubchem.ncbi.nlm.nih.gov/compound/3080913) often fails the toolkit energy tests but a small margin. I haven't looked into why, but the molecule is highly polar and probably sensitive to small errors in electrostatics handling.
* One of the tests comparing bond forces used decimal places when comparing numerical values that are much larger than one (order of 1000), resulting in a comparison criteria that was too strict.
> Test fixes

- devtools/conda-envs/minimal_env.yaml
- devtools/conda-envs/test_env.yaml
- openff/interchange/tests/components/test_interchange.py
Small fix for a (not-really-public) API change in the new release. I don't want to put effort toward maintaining compatibility with older versions of the toolkit and will keep this pinned in tests unless there's a compelling reason not to.
> Pin to OpenFF Toolkit 0.10.0+

- pytest.ini
CI logs are clogged with hundreds of lines of warnings about unregistered marks, which I don't see locally because I was using an untracked file. I pretty much copied the configuration from [the docs](https://docs.pytest.org/en/6.2.x/example/markers.html#registering-markers). When I run the entire suite locally, I get only a few warnings:
```
================================================================================= warnings summary ==================================================================================
../../miniconda3/envs/openff-system/lib/python3.8/site-packages/past/builtins/misc.py:45
/Users/mwt/miniconda3/envs/openff-system/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the …
```
> Add pytest.ini

- .github/workflows/ci.yaml
- .github/workflows/ci_minimal.yaml
- .github/workflows/cron.yaml
Motivated by https://github.com/openforcefield/openff-toolkit/pull/1043; I thought `mamba-version="*"` was enough to use `mamba` throughout, but that might not the case. I'm not entirely sure which of [these (many) options](https://github.com/conda-incubator/setup-miniconda) are and are not used; I have to say it's not ideal to need to use 8+ options to get fast environment creation.
> Use mambaforge

- devtools/conda-envs/test_env.yaml
- docs/installation.md
- openff/interchange/drivers/amber.py
- openff/interchange/exceptions.py
- openff/interchange/interoperability_tests/internal/test_amber.py
- setup.cfg
There's a ~0.02 kJ/mol/molecule in each term that I'm having a hard time isolating. Could be some rounding in some step, but everything looks to be passed around with 6+ digits of precision ...
> Improve parity of Amber energy driver and exports

- openff/interchange/components/potentials.py
- openff/interchange/unit_tests/components/test_smirnoff.py
> Refactor matrix exports

- devtools/conda-envs/test_env.yaml
- openff/interchange/interop/internal/gromacs.py
- openff/interchange/interoperability_tests/internal/test_gromacs.py
This PR adds a function `from_gro` that returns a stripped down `Interchange` object containing only positions and box vectors.
> Add native GRO file reader

- .github/workflows/ci.yaml
- .github/workflows/ci_minimal.yaml
- devtools/conda-envs/minimal_env.yaml
- devtools/conda-envs/test_env.yaml
Apparently we are given multi-core VMs by default!?
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
> Add pytest-xdist to test envs

- openff/interchange/drivers/__init__.py
- openff/interchange/drivers/all.py
- openff/interchange/drivers/lammps.py
- openff/interchange/drivers/openmm.py
- openff/interchange/drivers/report.py
- openff/interchange/energy_tests/test_energies.py
- openff/interchange/interoperability_tests/internal/test_gromacs.py
- openff/interchange/interoperability_tests/test_openmm.py
- openff/interchange/unit_tests/drivers/test_report.py
This PR implements the logic portion of the objective of establishing a reference set of parametrized systems for testing. https://github.com/openforcefield/openff-interchange/issues/91 is related.
> Improvements to energy drivers

- .github/workflows/check-openmm-rc.yaml
- .github/workflows/test-openmm-rc.yaml
I don't think I can really validate the behavior until another RC is built, which will likely be several months.
Context: https://github.com/openmm/openmm/issues/3232#issuecomment-909478595
> Add actions that automatically check for OpenMM RC builds

- openff/interchange/types.py
- openff/interchange/unit_tests/test_types.py
This is a possible solution for #307. I ran into this case (a `np.float64` wrapped as an `openmm.unit.Quantity`) while working with ForceBalance. It's somewhat hard-coded to this specific case but should catch some others.
> Handle NumPy duck-typing built-ins

- openff/interchange/components/base.py
- openff/interchange/interop/intermol.py
- openff/interchange/interop/internal/gromacs.py
- openff/interchange/interop/openmm.py
- openff/interchange/interoperability_tests/internal/test_gromacs.py
- setup.cfg
- stubs/mdtraj/__init__.pyi
This PR adds a not-fully-scoped GROMACS topology reader. As of today I can round-trip a test file into something that looks decent for the sections that are implemented; I have not yet tested if they will run.
It currently is little more than a converted from an InterMol object, which is responsible for the heavy lifting. I may continue to build out that conversion layer, but I will also start to refactor it out in favor of internal parsers. I have found InterMol's object models to be more straightforward so far, and I hope they are a more feasible starting point for refactoring than ParmEd.
Part of this necessarily chips away at #301, especially while upstream functionality in the toolkit is not yet being worked on.
Note that full - or even just generally useful - GROMACS parsers are …
> Add GROMACS topology reader and InterMol converter

- openff/interchange/drivers/all.py
- openff/interchange/drivers/amber.py
- openff/interchange/exceptions.py
- openff/interchange/unit_tests/drivers/test_all.py
- setup.cfg
I implemented `get_all_energies` in a naive and unsafe way, resulting in errors when any driver is not installed. Now, a row is skipped if the driver is uninstalled and/or fails (this could be changed later to be more robust).
In an environment with AmberTools forcefully removed:
```
In [18]: !which antechamber
antechamber not found
In [19]: !which sander
sander not found
In [20]: get_summary_data(out)
Out[20]:
Bond      Angle    Torsion       vdW  Electrostatics
OpenMM   2.222557  72.962517  15.890858 -0.267811      -27.622730
Gromacs  2.222573  72.962593  15.890857 -0.264045      -27.627102
LAMMPS   2.222439  72.962517  15.890873 -0.271789      -27.611731
```
> Skip unavailable drivers instead of erroring out

- openff/interchange/types.py
Might fix #345, although as discussed there it's not tested in our current infrastructure and may or may not actually be relevant.
> Fix setting byte order while processing bytes to NumPy arrays

- openff/interchange/components/interchange.py
- openff/interchange/unit_tests/components/test_interchange.py
This PR updates the behavior of `Interchange.__add__` to set the positions to `None` if either input `Interchange` object is missing positions. Currently, it will error out with no helpful message.
Pesudocode:
```python3
a: Interchange = Interchange.from_x(...)
a.positions = None
b: Interchange = Interchange.from_x(...)
b.positions = None
(a + b).positions
a.positions = some_positions_array
(a + b).positions
b.positions = some_positions_array
(a + b).positions
```
> Update positions processing in `Interchange.__add__`

- .github/workflows/beta.yaml
- .github/workflows/ci.yaml
- .github/workflows/ci_minimal.yaml
- .github/workflows/cron.yaml
- .pre-commit-config.yaml
- openff/interchange/energy_tests/test_energies.py
- openff/interchange/interoperability_tests/internal/test_amber.py
- openff/interchange/interoperability_tests/internal/test_gromacs.py
- openff/interchange/interoperability_tests/test_openmm.py
- openff/interchange/unit_tests/drivers/test_all.py
- pytest.ini
- setup.cfg
Slow tests (hitting a ton of AM1-BCC calculations, running entire liquid boxes, or other energy tests) slow down my development on my poor little hardware, so I am turning them off in the default configuration, but letting them run completely in CI. `pytest -v openff --durations=20 -m slow` now runs in about 40 seconds, down from several minutes.
> Update pytest and pre-commit configurations

- .github/workflows/beta.yaml
- .github/workflows/ci.yaml
- .github/workflows/ci_minimal.yaml
- .github/workflows/cron.yaml
- docs/developing.md
This PR removes Python 3.7 from CI and updates the developer docs accordingly. The next release will constrain `python >=3.8` at install time.
NumPy removed support for Python 3.7 last month as described in [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html).
> Drop support for Python 3.7

- devtools/conda-envs/docs_env.yaml
- docs/conf.py
- openff/interchange/components/foyer.py
Closes #378, which was due to `openff/interchange/components/foyer.py` having a `foyer` import outside the check that the package exists. This caused imports of this particular module to fail when foyer is unavailable, such as in the RTD environment. Tests that imports are successful on different environments might be worth looking into. 
This PR also updates Sphinx to 4.4.0, which comes with a lot of improvements to the API docs (and has a marginally more informative error message for the above problem)
> Fix RTD build and update Sphinx

- openff/interchange/components/interchange.py
- openff/interchange/components/toolkit.py
- openff/interchange/tests/__init__.py
- openff/interchange/tests/unit_tests/components/test_interchange.py
- openff/interchange/tests/unit_tests/components/test_toolkit.py
A quick pass at safeguarding against https://github.com/openforcefield/openff-toolkit/issues/716
> The desired behavior would be to raise an exception if the ESHandler doesn't exist, but the system has partial charges that will interact.
>  Error out if passed a force field missing required Electrostatics

- openff/interchange/interop/openmm.py
This PR follows https://github.com/openforcefield/openff-toolkit/pull/1198. I'll need to double-check some cases of LJPME and a switching function being applied, I don't think they're tested much yet.
> Update LJPME and/or switching logic in `to_openmm`

- .github/workflows/beta.yaml
- .github/workflows/ci.yaml
- .github/workflows/ci_minimal.yaml
- .github/workflows/cron.yaml
- .github/workflows/examples.yaml
- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/examples_env.yaml
- devtools/conda-envs/minimal_env.yaml
- devtools/conda-envs/test_env.yaml
- examples/protein_ligand/protein_ligand.ipynb
I _think_ that using https://github.com/codecov/codecov-action removes the need to install the `codecov` conda package.
> Split out examples in CI, trim some heavy/unused test dependencies

- devtools/conda-envs/docs_env.yaml
The docs builds have been failing for a while with some cryptic errors at the end of the logs. However, there are some useful errors at the beginning thanks to #382
> Fix RTD builds

- openff/interchange/components/interchange.py
- openff/interchange/tests/unit_tests/components/test_interchange.py
As discussed in #408, this simplifies an important route through the API by removing the need for the user to construct a `Topology` directly. This should allow many users to remove `Topology` from their mental model of the OpenFF ecosystem.
> Allow from_smirnoff to take a list of Molecules instead of a Topology

- .github/workflows/ci.yaml
- openff/interchange/tests/interoperability_tests/internal/test_amber.py
I realize that for a while now, CI runners _always_ had access to OpenEye toolkits. I'm not interested in exhaustively testing toolkit wrapper behaviors (that's a job for the OpenFF Toolkit) but I do want to ensure a developer without an OpenEye license can run the test suite without major surprises.
> Add non-OpenEye jobs to CI matrix

- .pre-commit-config.yaml
- examples/SMIRNOFF_simulation.ipynb
- examples/conformer_energies.ipynb
- examples/foyer-showcase/solvated-nanoparticle.ipynb
- examples/optimize-with-jax.ipynb
- examples/packed_box.ipynb
- examples/parameter_replacement.ipynb
- examples/parameter_splitting.ipynb
- examples/protein_ligand/protein_ligand.ipynb
- examples/smirnoff_argon.ipynb
- examples/smirnoff_ethanol.ipynb
I'm getting impatient with notebooks providing noisy diffs and forgetting if I should run before committing (slow) or clearing and saving. Ideally there's automation that keeps the output saved in a way that keeps the files up-to-date for wandering eyes but does not get in the way of development. Short of that I'm using [`nbstripout`](https://github.com/kynan/nbstripout) to standardize everything on empty outputs.
If others feel strong enough and/or can provided other tools that reduce this friction I'd be happy to adopt them.
> Add nbstripout

- .pre-commit-config.yaml
- openff/interchange/components/interchange.py
- openff/interchange/interop/internal/gromacs.py
- openff/interchange/interop/openmm.py
- openff/interchange/tests/interoperability_tests/internal/test_gromacs.py
#415 fixed (for the most part) how partial charges are assigned when virtual sites are involved but left fixing geometry for another PR. This is that PR.
Geometries appear to be matching @j-wags's test set. Intramolecular exclusions still differ for most/all cases. Energies match for the case of `exclusion_policy="parents"` but no others.
> Fix assigning virtual site geometries and intramolecular exclusions through OpenMM

- openff/interchange/components/smirnoff.py
- openff/interchange/tests/unit_tests/components/test_smirnoff.py
The idivf parameter in improper torsions is [hard-coded to 3.0](https://github.com/openforcefield/openff-interchange/blob/v0.2.0-alpha.3/openff/interchange/components/smirnoff.py#L726), despite it being a parameter in the force field. If it's not set, the toolkit [sets](https://github.com/openforcefield/openff-toolkit/blob/8533e71b7d3a8c88699f91b55a87d9d6ff92b795/openff/toolkit/typing/engines/smirnoff/parameters.py#L3347-L3349) it to be 3.0. As far as I can tell, every SMIRNOFF-style force field in the universe chooses not to set it, so setting it to 3.0 did not adversely affect use of any released force field.
Thanks to @SimonBoothroyd whose work uncovered this bug and @j-wags who navigated me through the turbulent waters of idivf.
> Fix storing improper idivf

- setup.cfg
Because it's not cheating the metrics if it's never meant to be available at runtime.
> Ignore `if TYPE_CHECKING` lines in test coverage

- docs/using/output.md
- examples/lammps/.gitignore
- examples/lammps/lammps.ipynb
- openff/interchange/components/mdconfig.py
- openff/interchange/tests/unit_tests/drivers/test_all.py
This PR adds book-style documentation to the new `MDConfig` object and adds it to the LAMMPS example. The Amber example is still in PR and there is no GROMACS example until performance improves, so other uses of `MDConfig` are not yet in examples.
- The LAMMPS example crashes with `special_bonds lj 0 0.5 1 coul 0 0.8333333333 1`, as outputted by MDConfig. The previous value of `special_bonds lj 0.0 0.0 0.5 coul 0.0 0.0 0.8333333333`, which IIRC was previously produced by `_write_lammps_input_file()`, works with the other changes to the sample file. I think this is an error/regression in MDConfig? I tried changing the 0s and 1s to 0.0s and 1.0s in case it was an int/float error but no dice. I've left the new value in the example as a reminder not to merge until we sort this out.
- Have we …
> Mdconfig docs

- openff/interchange/drivers/gromacs.py
- openff/interchange/drivers/lammps.py
- openff/interchange/tests/__init__.py
- openff/interchange/tests/unit_tests/drivers/test_all.py
Closes #149 
This works locally with a `gmx_mpi` executable in my environment, pulled in from
```shell
$ mamba install "gromacs >=2021=mpi_openmpi_h*" -c conda-forge
```
(Just grabbing `"gromacs >=2021=mpi*"` pulls in a double-precision MPI build)
I'm not too interested in adding these cases to CI at the moment. If these become common use cases and/or pain points for users we can revisit that.
> Auto-detect GROMACS and LAMMPS executables

- openff/interchange/interop/openmm.py
- openff/interchange/tests/unit_tests/interop/test_openmm.py
Implements https://github.com/openforcefield/openff-toolkit/issues/1102
This will not be implemented in other engines until it's clear to me that this behavior properly supported.
> Allow creation of OpenMM `System`s with no non-bonded forces

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
- .github/ISSUE_TEMPLATE/USER_SUPPORT.md
I only now realized we don't have issue templates - this might explain why I'm not seeing i.e. `conda list` outputs.
> Add issue templates

- openff/interchange/interop/openmm.py
- openff/interchange/tests/data/no_vdw.offxml
- openff/interchange/tests/interoperability_tests/internal/test_gromacs.py
- openff/interchange/tests/interoperability_tests/test_openmm.py
> Allow creation of `openmm.System` with no vdW parameters

- openff/interchange/interop/internal/gromacs.py
> Deduplicate unique molecules in GROMACS export

- openff/interchange/interop/openmm.py
- openff/interchange/tests/data/tip5p.offxml
- openff/interchange/tests/interoperability_tests/test_openmm.py
This fixes a bug in which non-bonded exceptions aren't properly added between particles on adjacent or the same parent molecule, i.e. in TIP5P water.
> Fix particle-particle exceptions in OpenMM

- openff/interchange/interop/openmm.py
- openff/interchange/tests/interoperability_tests/test_openmm.py
This is the band-aid promised in #484.
> Ensure cutoffs match when multiple nonbonded forces are used

- openff/interchange/interop/internal/gromacs.py
- openff/interchange/tests/interoperability_tests/internal/test_gromacs.py
This is strictly an invalid modification of users' inputs, but I would rather warn than raise an exception here unless user feedback disagrees.
> Add warning about overriding missing box vectors in GRO writer

- .github/workflows/ci_minimal.yaml
- devtools/conda-envs/minimal_env.yaml
- openff/interchange/components/smirnoff.py
- setup.cfg
I don't know how many times I'll have to nurse CodeCov into doing what I want, but here goes another attempt:
> Fix code coverage

- openff/interchange/components/smirnoff.py
Uses ParameterList slicing instead of `get_parameter` to look up parameters by their SMIRKS. Cuts `ff.create_interchange` runtime by about 40%. 
Test code:
```python
%load_ext snakeviz
from openff.toolkit import Molecule, OpenEyeToolkitWrapper, RDKitToolkitWrapper, ForceField, Topology
from openff.toolkit.utils import get_data_file_path
ff = ForceField('openff-2.0.0.offxml', 'ff14sb_off_impropers_0.0.3.offxml')
protein = Molecule.from_polymer_pdb(get_data_file_path('proteins/T4-protein.pdb'))
ala = Molecule.from_polymer_pdb(get_data_file_path('proteins/MainChain_ALA.pdb'))
top = Topology()
top.add_molecule(protein)
for i in range(5):
top.add_molecule(ala)
water = Molecule.from_smiles('O')
for i in range(50):
top.add_molecule(water)
```
```python
%%snakeviz
interchange = …
```
> Faster parameter lookup

- openff/interchange/tests/unit_tests/components/test_smirnoff.py
The default tolerances of [`pytest.approx`](https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest-approx) are a little too strict for Wiberg bond order interpolation via our wrapped toolkits. This causes many false negatives in tests.
> Loosen tolerance in tests requiring Wiberg bond order interpolation

- openff/interchange/interop/openmm/__init__.py
- openff/interchange/tests/interoperability_tests/test_openmm.py
While working on #513 I noticed that `from openff.interchange.interop.openmm._topology import to_openmm_topology` is ... not exactly peak user experience. Here I reorganized `openmm/__init__.py` to include some of the functions I'd expect most users to need to access.
I also added a strong warning in `from_openmm` and hid some imports away in helper functions since I don't think those will be used much soon.
cc: @Yoshanuikabundi - another ping! Hooray! I think this is what you have in mind for `__all__` usage?
> Re-organize `openff.interchange.interop.openmm` API

- .github/workflows/examples.yaml
- examples/ligand_in_water/ligand_in_water.ipynb
This PR updates the ligand-in-water notebook after we figured out the reasons for the simulations crashing (https://github.com/openmm/openmm/issues/3736) and virtual particle ordering.
@Yoshanuikabundi do you think it would be worth including short GROMACS simulations in this notebook? One one hand, it's a common user need (https://github.com/openforcefield/openff-toolkit/issues/1328) and not _that_ much of a leap from running the same state in OpenMM. On the other hand, it takes a significant amount of cruft to run GROMACS simulations in notebooks and the scope boundary here is hard to define - should the same be done when we support many engines?
> Update ligand in water notebook

- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/examples_env.yaml
- devtools/conda-envs/test_env.yaml
- environment.yml
- openff/interchange/components/foyer.py
- openff/interchange/components/smirnoff.py
- openff/interchange/drivers/report.py
- openff/interchange/tests/unit_tests/components/test_foyer.py
Foyer 0.11.3 adds a `TopologyGraph.from_openff_topology` method that works with the new stack. I found Interchange was previously using some temporary code, which can now be removed.
> Updates for new Foyer `TopologyGraph` API

- openff/interchange/interop/internal/amber.py
- openff/interchange/tests/interoperability_tests/internal/test_amber.py
Minor follow-on to #538, only adding a test and opening with access to the organization's OpenEye license
> Fix zero-residue Amber export

- openff/interchange/interop/internal/amber.py
Interchange.to_prmtop produces an invalid file when the number of residues is zero.   Here is an example:
from openff.toolkit import ForceField, Molecule, Topology
from openff.interchange import Interchange
import parmed
mol = Molecule.from_file("system.sdf")
top = Topology.from_molecules(mol)
ff = ForceField("openff-2.0.0.offxml")
itc = Interchange.from_smirnoff(force_field=ff, topology=top)
itc.to_prmtop("system.prmtop")
itc.to_inpcrd("system.inpcrd")
pmd = parmed.amber.AmberParm("system.prmtop")
This results in:
File "/scratch/miniconda3/lib/python3.9/site-packages/parmed/amber/_amberparm.py", line 173, in __init__
self.initialize_topology(xyz, box)
File "/scratch/miniconda3/lib/python3.9/site-packages/parmed/amber/_amberparm.py", line 203, in initialize_topology
self.load_structure() …
> Fix handling of zero-residue case in prmtop export.

- .github/workflows/ci.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/docs_env.yaml
- devtools/conda-envs/test_env.yaml
- docs/releasehistory.md
- openff/interchange/interop/internal/lammps.py
Fixes #544 
```python
In [1]: from openff.toolkit import Molecule, ForceField
...: from openff.interchange import Interchange
...: from openff.units import unit
...: import numpy
...:
...:
...: molecule = Molecule.from_smiles('C1=CN=CN1')
...: sage = ForceField("openff_unconstrained-2.0.0.offxml")
...: molecule.generate_conformers()
...: cubic_box = unit.Quantity(10.0 * numpy.eye(3), unit.angstrom)
...:
...: interchange = Interchange.from_smirnoff(topology=[molecule], force_field=sage, box=cubic_box)
...: interchange.to_lammps("imidazole.lmp")
/Users/mattthompson/mambaforge/envs/openff-interchange-env/lib/python3.9/site-packages/smirnoff99frosst/smirnoff99frosst.py:11: UserWarning: Module openff was already imported from None, but /Users/mattthompson/software/openff-interchange is being …
```
> List the central atom first in CVFF style dihedrals in LAMMPS export

- .pre-commit-config.yaml
- devtools/conda-envs/docs_env.yaml
- openff/interchange/components/interchange.py
- openff/interchange/tests/unit_tests/interop/test_openmm.py
> Use `Interchange.box` when exporting to PDB via OpenMM

- docs/releasehistory.md
- openff/interchange/components/interchange.py
The historical behavior of the OpenFF stack (and the [current behavior](https://github.com/openforcefield/openff-toolkit/blob/0.11.4/openff/toolkit/typing/engines/smirnoff/forcefield.py#L1128)) is to attempt to combine all non-bonded forces into a single `openmm.NonbondedForce` object. This change makes that behavior the default.
> Combine non-bonded forces by default

- openff/interchange/__init__.py
- openff/interchange/tests/unit_tests/test_lazy_import.py
```shell
$ git checkout upstream/main && time python -c "from openff.interchange import __version__" && git checkout top-level-lazy-import && time python -c "from openff.interchange import __version__"
HEAD is now at 6222adc Merge pull request #566 from openforcefield/refactor-report
python -c "from openff.interchange import __version__"  1.79s user 0.76s system 88% cpu 2.899 total
Previous HEAD position was 6222adc Merge pull request #566 from openforcefield/refactor-report
Switched to branch 'top-level-lazy-import'
python -c "from openff.interchange import __version__"  0.04s user 0.04s system 83% cpu 0.096 total
```
> Lazy load `Interchange` at top level

- openff/interchange/exceptions.py
- openff/interchange/smirnoff/_create.py
- openff/interchange/smirnoff/_valence.py
- openff/interchange/tests/energy_tests/test_energies.py
- openff/interchange/tests/interoperability_tests/test_openmm.py
- openff/interchange/tests/unit_tests/interop/test_openmm.py
- openff/interchange/tests/unit_tests/smirnoff/test_create.py
- openff/interchange/tests/unit_tests/smirnoff/test_valence.py
* Raise `ValueError` if `partial_bond_orders_from_molecules` contains isomorphic duplicates
* Do not look in `test_forcefields/`
> Updates to match toolkit behaviors

- docs/releasehistory.md
- examples/conformer_energies.ipynb
- examples/experimental/openmm-import/protein-ligand.ipynb
- openff/interchange/drivers/amber.py
- openff/interchange/drivers/gromacs.py
- openff/interchange/drivers/lammps.py
- openff/interchange/drivers/openmm.py
- openff/interchange/interop/external.py
- openff/interchange/interop/internal/amber.py
- openff/interchange/interop/internal/gromacs.py
- openff/interchange/interop/internal/lammps.py
- openff/interchange/interop/openmm/__init__.py
- openff/interchange/interop/openmm/_nonbonded.py
- openff/interchange/interop/openmm/_valence.py
- openff/interchange/interop/parmed.py
- openff/interchange/smirnoff/_create.py
- openff/interchange/smirnoff/_virtual_sites.py
- openff/interchange/tests/__init__.py
- openff/interchange/tests/energy_tests/test_energies.py
- openff/interchange/tests/interoperability_tests/internal/test_amber.py
- openff/interchange/tests/interoperability_tests/internal/test_gromacs.py
- openff/interchange/tests/interoperability_tests/internal/test_lammps.py
- openff/interchange/tests/interoperability_tests/test_openmm.py
- openff/interchange/tests/unit_tests/components/test_interchange.py
- openff/interchange/tests/unit_tests/components/test_toolkit.py
I've run into a handful of arguments named i.e. `vdw_handler` when the type is `SMIRNOFFvdWCollection`. There are also some uses of `openff_sys` and similar patterns. Changing argument names is not free but I'd like to do it sooner than later. For example:
```diff
def get_amber_energies(
-    off_sys: Interchange,
+    interchange: Interchange,
writer: str = "internal",
electrostatics: bool = True,
) -> EnergyReport:
```
> Rename more arguments away from outdated names

- .github/workflows/ci.yaml
- openff/interchange/interop/openmm/_nonbonded.py
- plugins/nonbonded_plugins/nonbonded.py
This is an inconsistency that caused me trouble working on https://github.com/openforcefield/smirnoff-plugins/pull/53. It's somewhat tricky because
* `openmm.NonbondedForce` will gladly take in `openmm.unit.Quantity`s but `openmm.CustomNonbondedForce` wants floats.
* Some functional forms have global parameters, which may or may not have units.
* Some functional forms have  pre-compute parameters, which could strip units
So, by the time parameters are [given](https://github.com/openforcefield/openff-interchange/blob/5ceba6c78bf3ebeecdb7b96355b8424bafc3ab19/openff/interchange/interop/openmm/_nonbonded.py#L949) to OpenMM's C++ layer, it's not clear if their units were stripped or not, and which units they were in. This remains a potent footgun but I'm not going to be able to put in all of …
> Consistently strip units when passing parameters to `openmm.CustomNonbondedForce`

- docs/releasehistory.md
- docs/using/plugins.md
- openff/interchange/smirnoff/_create.py
This is #648 moved onto a new branch.
> Support multiple `ParameterHandler`s in one `SMIRNOFFCollection` plugin

- openff/interchange/smirnoff/_create.py
Responds to [Issue#647](https://github.com/openforcefield/openff-interchange/issues/647)
I have left comments in the code block regarding:
1. If more than one collection is loaded by the plugin.
2. If there is only one handler in the collection.
> Support multiple `ParameterHandlers` in one `SMIRNOFFCollection`

- docs/conf.py
- docs/installation.md
- docs/using/plugins.md
This PR links the installation guide to the new [ecosystem docs](https://docs.openforcefield.org/en/latest/install.html).
> Bring installation guide in line with ecosystem docs

- openff/interchange/_tests/unit_tests/interop/gromacs/models/test_models.py
- openff/interchange/interop/gromacs/_import/_import.py
- openff/interchange/interop/gromacs/export/_export.py
- openff/interchange/interop/gromacs/models/models.py
- openff/interchange/smirnoff/_gromacs.py
This PR introduces two methods for adding and removing molecules from `GROMACSSystem`s. This can be useful for a handful of operations, a flashy one being re-parametrizing a ligand in a protein-ligand (+ water and ions) complex with a different force field without needing to re-parametrize or do anything in particular to the protein.
> Add methods for adding and removing GROMACS molecules

- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/test_env.yaml
This was downpinned to avoid an incompatibility with Pydantic which I think is now resolved.
> Update `mypy` pin

- devtools/conda-envs/docs_env.yaml
- docs/using/plugins.md
- openff/interchange/components/packmol.py
Toolkit 0.13.0 broke the docs environment - it would solve but then `from openff.toolkit import Molecule, ForceField, Topology` would raise an ImportError. I just copied over the deps from the test environment and it seems to work, so hopefully this is some change in a dependency that is already reflected in the forge recipe. Also tidied up the pack_box docstring.
> Fix docs environment and tidy up pack_box docstring

- .github/workflows/examples.yaml
- .readthedocs.yml
- devtools/conda-envs/docs_env.yaml
- openff/interchange/_experimental.py
- openff/interchange/_tests/unit_tests/interop/gromacs/_import/test_from_files.py
- openff/interchange/_tests/unit_tests/interop/gromacs/_import/test_topology.py
- openff/interchange/_tests/unit_tests/interop/gromacs/test_interchange.py
- openff/interchange/_tests/unit_tests/interop/openmm/_import/test_import.py
- openff/interchange/_tests/unit_tests/test_experimental.py
- openff/interchange/exceptions.py
- openff/interchange/interop/gromacs/_import/_import.py
- openff/interchange/interop/gromacs/_interchange.py
- openff/interchange/interop/openmm/_import/_import.py
This is an idea I've considered for a while but never tried. The problem is that many features need extensive testing to be considered complete yet need to exist in the package for a long time in order for that testing to be feasible. Throwing warnings around is not ideal as they can easily be ignored by users. Me personally and repeatedly communicating the nature of these features scales poorly and guarantees that some people aren't informed what is and is not currently trustworthy. Hiding things behind "private" import paths implies a lack of API stability but does not communicate whether or not something is trustworthy and leaves us more or less in the same position as before.
With this changeset, features tagged with an `@experimental` decorator require an environment variable …
> Tag some features as opt-in experimental

- devtools/conda-envs/dev_env.yaml
- openff/interchange/interop/openmm/_nonbonded.py
This PR fixes an assumption in the OpenMM export logic that a vdW collection exists with that name as a non-plugin.
> FIX: Do not assume vdW handler exists

- docs/releasehistory.md
- openff/interchange/interop/gromacs/export/_export.py
#719 
I used this code to reproduce the issue and verify the fix, but it takes about 4 minutes to run so I can't include it in the test suite.
```python
from rdkit import Chem
from openmm.app import PDBFile
from openff.toolkit.topology import Molecule, Topology
from openff.toolkit.typing.engines.smirnoff import ForceField
from openff.interchange.components._packmol import pack_box
from openff.units import unit
from openff.interchange.components.mdconfig import MDConfig
from openff.interchange.drivers import get_gromacs_energies, get_openmm_energies
t0 = time.time()
molecules = [Molecule.from_smiles(smiles) for smiles in ['CCO', 'CCCO']]
n_molecules = [3030, 6600]
system_name = f'ethanol_propanol_{n_molecules[0]}_{n_molecules[1]}'
topology = pack_box(
molecules = molecules, …
```
> Wrap GROMACS atom indices at 100,000

- openff/interchange/_tests/unit_tests/components/test_mdconfig.py
- openff/interchange/components/mdconfig.py
For purposes of energy evaluation of systems prepared with a constrained force field, we want to ignore constrained interactions but **NOT** apply a constraint algorithm like SHAKE; when comparing energies to other engines, it is important that the input coordinates are used, **NOT** coordinates that have been adjusted to satisfy constraints. This breaks a soft convention of `ntc=ntf=2` in sander input files, but is justified by the use case not being production.
> Do not perform SHAKE in Amber driver

- docs/releasehistory.md
- openff/interchange/_tests/interoperability_tests/test_openmm.py
- openff/interchange/exceptions.py
Resolves #747. All exceptions now inherit from `OpenFFInterchangeException` to provide a sort of catch-all. Those that previously inherited from things other than `BaseException` still do.
> Do not inherit from `BaseException`

- examples/protein_ligand/protein_ligand.ipynb
The `protein_ligand` example is broken on 0.3.6 - it uses the old argument names for `pack_box`.
This PR gets everything to run without errors, but at least for me the summary data tables were not displaying.
> Fix protein_ligand example's call to pack_box

- examples/conformer_energies/conformer_energies.ipynb
- examples/experimental/openmm-import/protein-ligand.ipynb
- examples/experimental/openmmforcefields.ipynb
- examples/experimental/solvate/solvate.ipynb
- examples/lammps/lammps.ipynb
- examples/ligand_in_water/ligand_in_water.ipynb
- examples/openmm/openmm.ipynb
- examples/packed_box/packed_box.ipynb
- examples/protein_ligand/protein_ligand.ipynb
- examples/vectorized_representations/vectorized_representations.ipynb
- openff/interchange/components/interchange.py
This PR includes example refreshments in anticipation of the new examples page (https://github.com/openforcefield/openff-docs/pull/7)
> Central examples

- openff/interchange/drivers/gromacs.py
> Update gromacs.py to pass input edr path in _parse_gmx_energies routine

- README.md
This section adds a short section on citing, now that there is a Zenodo page set up.
> Add "how to cite" section

- .github/workflows/ci.yaml
- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/examples_env.yaml
- devtools/conda-envs/minimal_env.yaml
- devtools/conda-envs/test_env.yaml
- openff/interchange/_tests/unit_tests/components/test_interchange.py
- openff/interchange/_tests/unit_tests/smirnoff/test_valence.py
- openff/interchange/common/_nonbonded.py
- openff/interchange/common/_valence.py
- openff/interchange/components/_base.py
- openff/interchange/components/interchange.py
- openff/interchange/components/mdconfig.py
- openff/interchange/components/potentials.py
- openff/interchange/drivers/report.py
- openff/interchange/foyer/_nonbonded.py
- openff/interchange/foyer/_valence.py
- openff/interchange/interop/gromacs/models/models.py
- openff/interchange/models.py
- openff/interchange/smirnoff/_nonbonded.py
- openff/interchange/smirnoff/_virtual_sites.py
This PR extends https://github.com/openforcefield/openff-models/pull/27
> Use Pydantic v1 API from v2

- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/docs_env.yaml
- devtools/conda-envs/examples_env.yaml
- devtools/conda-envs/minimal_env.yaml
- devtools/conda-envs/test_env.yaml
- docs/releasehistory.md
- openff/interchange/_tests/data/buckingham.offxml
- openff/interchange/_tests/data/buckingham_virtual_sites.offxml
- openff/interchange/_tests/interoperability_tests/test_openmm.py
- openff/interchange/_tests/unit_tests/components/test_mdconfig.py
- openff/interchange/_tests/unit_tests/interop/openmm/test_nonbonded.py
- openff/interchange/_tests/unit_tests/smirnoff/test_create.py
- openff/interchange/common/_nonbonded.py
- openff/interchange/components/mdconfig.py
- openff/interchange/interop/openmm/_nonbonded.py
- openff/interchange/smirnoff/_create.py
- openff/interchange/smirnoff/_nonbonded.py
- plugins/nonbonded_plugins/nonbonded.py
Resolves #786
* `MDConfig`, `SMIRNOFFvdWCollection`, and similar classes now separately track vdW methods following [`OFF-EP-0008`](https://github.com/openforcefield/standards/blob/b3e17f72c7a906e0700f5d9605ffa9683a1ef32d/docs/enhancement-proposals/off-ep-0008.md).
* Only versions of the toolkit supporting vdW 0.4 (0.14.2+) are compatible
* Using plugins that create `openmm.NonbondedForce` now results in `openmm.NonbondedForce.NoCutoff` when the topology is non-periodic and `vdWHandler.nonperiodic_method == "no-cutoff"
* Some OFFXML files used in tests are updated manually in leiu of wiring up auto-converters.
> Internally use vdW section 0.4

- README.md
...to refer to 0.3.17 and the all-versions doi, respectively.
The zenodo links in the readme were linking to an old release. This PR fixes them, so that the first one links the current (Nov 3, 2023) release and the second one links the evergreen latest release.
> fixed the zenodo links 

- docs/releasehistory.md
- openff/interchange/_tests/unit_tests/interop/amber/export/test_export.py
- openff/interchange/interop/amber/export/_export.py
Related #783 #843 
Previously this silently produced garbage files; these will be implemented in the future, but explicitly erroring out is an improvement in the current state.
> Raise exception when writing Amber files with virtual sites

- docs/releasehistory.md
- openff/interchange/_tests/unit_tests/smirnoff/test_nonbonded.py
- openff/interchange/smirnoff/_nonbonded.py
Iterating on #842; this is the simplest solution we've come up with so far, I'm not sure it's necessarily the best.
> Fix sensitivity to atom ordering in charge caching

- docs/releasehistory.md
- openff/interchange/_tests/unit_tests/operations/minimize/test_openmm.py
- openff/interchange/exceptions.py
- openff/interchange/operations/minimize/openmm.py
> Improve minimization with virtual sites

- docs/developing.md
- docs/installation.md
Resolves #862
The docs default to the `stable` branch so these won't be highly visible until a release is made in early January.
> Update installation instructions

- .github/workflows/ci.yaml
- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/examples_env.yaml
There are some changes in 2023.2; for now it is important to get tests passing.
> Pin `openeye-toolkits =2023.1`

- .github/workflows/beta.yaml
- .github/workflows/ci.yaml
- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/docs_env.yaml
- devtools/conda-envs/examples_env.yaml
- devtools/conda-envs/test_env.yaml
- docs/releasehistory.md
- openff/interchange/_tests/interoperability_tests/test_openmm.py
- openff/interchange/_tests/unit_tests/components/test_interchange.py
- openff/interchange/_tests/unit_tests/interop/openmm/_import/test_import.py
- openff/interchange/components/_viz.py
- openff/interchange/components/interchange.py
- openff/interchange/components/toolkit.py
- openff/interchange/interop/openmm/__init__.py
- openff/interchange/interop/openmm/_import/_import.py
- openff/interchange/interop/openmm/_topology.py
- openff/interchange/smirnoff/_nonbonded.py
Related to https://github.com/openforcefield/openff-toolkit/pull/1818
> Interoperability trunk

- openff/interchange/_tests/unit_tests/interop/openmm/test_hmr.py
- openff/interchange/components/interchange.py
- openff/interchange/interop/openmm/__init__.py
#889 
Limitations:
* Only in OpenMM export
* No virtual sites are allowed
* No waters are affected, even if flexible
> Add partial HMR implementation to OpenMM export

- docs/releasehistory.md
- openff/interchange/_tests/unit_tests/interop/gromacs/export/test_export.py
- openff/interchange/_tests/unit_tests/smirnoff/test_gromacs.py
- openff/interchange/smirnoff/_gromacs.py
Resolves #911
When an `Interchange` has both bond parameters and constraints (with distances), constrained bonds are errneously given the bond length in the GROMACS `[ settles ]` section. SMIRNOFF says these should be given the constraint distances.
> Fix `[ settles ]` distances when bond parameters are present

- docs/releasehistory.md
- examples/host-guest/.gitignore
- examples/protein_ligand/protein_ligand.ipynb
- examples/virtual_sites/.gitignore
- openff/interchange/_tests/test_deprecations.py
- openff/interchange/_tests/unit_tests/components/test_interchange.py
- openff/interchange/components/interchange.py
`Interchange.__add__` is deprecated, rerouting to a new method `Interchange.combine` that includes the same logic.
This change is motivated by two key factors:
* `object.__add__` is a little magical and might interact surprisingly with standard expectations of Python classes
* The `+` operator cannot take arguments or return extra information. This makes it impossible to pass optional settings to the function or clearly return information about any transformations, i.e. mapping of residue information between input and output.
Thanks to @richardjgowers for the suggestion
cc: @pbuslaev - this is a non-erroring renaming of the function, so if you were working on any tests please update the ` + `. The business logic should be unchanged as of now
> Deprecate `Interchange.__add__`, rename to `Interchange.combine`

- openff/interchange/_tests/conftest.py
- openff/interchange/_tests/energy_tests/interop/amber/__init__.py
- openff/interchange/_tests/energy_tests/interop/amber/test_energies.py
> Test intramolecular interactions in polycyclic systems with Amber

- docs/releasehistory.md
- openff/interchange/_tests/unit_tests/interop/openmm/_import/test_compat.py
- openff/interchange/components/interchange.py
- openff/interchange/interop/openmm/_import/_import.py
- openff/interchange/interop/openmm/_import/compat.py
> Raise errors when `from_openmm` inputs are incompatible or unsupported

- .github/workflows/ci.yaml
- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/test_env.yaml
- docs/releasehistory.md
- openff/interchange/_tests/data/hexanol-water.pdb
- openff/interchange/_tests/interoperability_tests/test_openmm.py
- openff/interchange/_tests/unit_tests/interop/openmm/test_virtual_sites.py
- openff/interchange/interop/openmm/_nonbonded.py
- openff/interchange/operations/minimize/openmm.py
This change fixes the particle collation issue that caused #919
> Add tests with virtual sites and split forces

- examples/ligand_in_water/ligand_in_water.ipynb
- openff/interchange/_tests/unit_tests/interop/test_virtual_sites.py
- openff/interchange/interop/_virtual_sites.py
- openff/interchange/smirnoff/_gromacs.py
This PR adds an argument to `get_positions_with_virtual_sites(..., collate=False)` which brings the logic up to date with the rest of the topological and physical information. This should resolve #931 and #941
> Optionally collate virtual site positions in getter

- docs/using/plugins.md
This fixes the link mentioned in https://github.com/openforcefield/openff-interchange/pull/878/files#r1471815719
Unfortunately I'm not sure why the original link ever worked. MyST went through a stage of frequently breaking links, but I thought we were still on a version of MyST prior to that.
This PR restores the link, but makes it point to the whole Toolkit developer page instead of the particular subsection. If we want to point to the subsection, we need a PR to the Toolkit to give the subsection a reference anchor so that it appears in the Intersphinx inventory.
> Restore link to Toolkit docs

- .pre-commit-config.yaml
- openff/interchange/_tests/interoperability_tests/components/test_packmol.py
- openff/interchange/_tests/unit_tests/components/test_packmol.py
- openff/interchange/components/_packmol.py
`solvate_topology` is written in a way that makes it fairly tricky to use non-water, so I grumble grumble made a new method. I was tempted to make the existing method `hydrate_topology` mirroring how people talk about solvation in water and non-water generally, but I don't think people use that language in system preparation steps.
This can all be done with `pack_box`, but this makes it a little easier.
> Add non-water solvation helper function

- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/examples_env.yaml
Some funky stuff happened with 0.3.7; I don't doubt it'll be fixed soon, this just down-constrains to a slightly older version.
> Constrain to `openff-nagl ==0.3.6`

- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/examples_env.yaml
- openff/interchange/_tests/unit_tests/smirnoff/test_nonbonded.py
- openff/interchange/smirnoff/_nonbonded.py
> Use better NAGL constraints

- .pre-commit-config.yaml
- docs/releasehistory.md
- openff/interchange/_tests/unit_tests/interop/openmm/_import/test_import.py
- openff/interchange/interop/openmm/_import/_import.py
Resolves #971 
At some point I recently set the default "cutoff" of the base electrostatics class to 10 A, differing from SMIRNOFF's 9 A, partially because it's OpenMM's default but mostly to avoid it drifting away from really being a base class. Previously they were all set to 9 A so this conflict never arose; now it's as simple as setting it when parsing. This will surely get more complicated when we consider non-PME settings.
> Ensure electrostatics "cutoff" is set in `from_openmm`

- openff/interchange/_tests/unit_tests/interop/gromacs/export/test_export.py
- openff/interchange/components/interchange.py
- openff/interchange/drivers/gromacs.py
- openff/interchange/interop/gromacs/export/_export.py
- setup.cfg
> Upstream GROMACS atom type merging

- devtools/conda-envs/examples_env.yaml
- openff/interchange/_tests/unit_tests/interop/gromacs/export/test_export.py
- openff/interchange/_tests/unit_tests/interop/gromacs/models/test_models.py
- openff/interchange/components/interchange.py
- openff/interchange/operations/_combine.py
- openff/interchange/smirnoff/_gromacs.py
> Ensure molecule names are unique at GROMACS export time

- openff/interchange/_tests/unit_tests/components/test_packmol.py
- openff/interchange/components/_packmol.py
> Improve PACKMOL failure handling, loading >99,999 atoms

- openff/interchange/components/_packmol.py
This is a simpler, and I think better, fix for #984 than #985
I did some rough benchmarking and for systems between 100,000 and 1,000,000 atoms, the time it takes to load coordinates is several of orders of magnitude less than the time it takes to actually pack the coordinates. So I'm not worried about optimizing this one-liner right now.
> More directly parse packed coordinates

- openff/interchange/_tests/unit_tests/interop/lammps/export/test_lammps.py
- openff/interchange/interop/lammps/export/export.py
Follow-up to recommendations made in [Issue 999](https://github.com/openforcefield/openff-interchange/pull/999)
> LAMMPS non-unique molecule ID hotfix

- docs/index.md
- docs/using/edges.md
- openff/interchange/components/interchange.py
In part resolves #1004 #1005 #1007
> Improve documentation of `from_openmm` and related features

- docs/releasehistory.md
- openff/interchange/_tests/__init__.py
- openff/interchange/_tests/data/example-sigma-hole-bromine.offxml
- openff/interchange/_tests/test_issues.py
- openff/interchange/smirnoff/_gromacs.py
- openff/interchange/smirnoff/_nonbonded.py
Resolves #1022
I'm confused how the ligand-in-water example was working previously, since this may cause the incorrect non-bonded (both vdW and electrostatics) parameters to be looked up on molecules placed in a topology after a virtual site-bearing molecule.
> Fix indexing in vdW lookup of atoms in GROMACS export

- docs/releasehistory.md
- openff/interchange/_tests/interoperability_tests/internal/test_gromacs.py
- openff/interchange/_tests/unit_tests/components/test_interchange.py
- openff/interchange/_tests/unit_tests/interop/gromacs/export/test_export.py
- openff/interchange/interop/gromacs/export/_export.py
This PR removes support for writing files to GROMACS simulations if no box vectors are defined.
Resolves #1029
> Do not write vacuum simulations to GROMACS files

- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/docs_env.yaml
- devtools/conda-envs/examples_env.yaml
- devtools/conda-envs/test_env.yaml
- openff/interchange/_tests/test_issues.py
This PR adds a sort of regression test for the behavior observed in #1031. The fix is actually in the toolkit (though in a pinch it would have been possible to add some bubblegum-and-paperclips here) and is expected to land in release 0.16.4 early next week (8/19 or so).
> Test that atom names are processed in `Interchange.from_openmm`

- devtools/conda-envs/dev_env.yaml
- openff/interchange/_tests/interoperability_tests/internal/test_gromacs.py
- openff/interchange/_tests/unit_tests/interop/gromacs/export/test_export.py
- openff/interchange/_tests/unit_tests/interop/openmm/test_virtual_sites.py
- openff/interchange/components/interchange.py
- openff/interchange/interop/gromacs/export/_export.py
Does something with #1016
Fixes #1028
> Test more cases of handling GROMACS residue IDs

- docs/releasehistory.md
- openff/interchange/_annotations.py
- openff/interchange/_tests/test_issues.py
- openff/interchange/common/_nonbonded.py
- openff/interchange/components/potentials.py
- openff/interchange/smirnoff/_nonbonded.py
> Fix default `.charges`

- openff/interchange/common/_nonbonded.py
- openff/interchange/smirnoff/_nonbonded.py
Minor update to #1066 to include `_charges` in the model definition. I still don't know why this is required, but it seems to work in my local tests. I just realized that it might be necessary to do `self._charges.clear()` before `self._charges.update()` to avoid mixing charges. I read the `if` condition as `len == 0 and ...` instead of `or`, which could possibly allow `update` to be called on a dict already containing some charges.
> Use update instead of assignment to set _charges

- openff/interchange/_tests/unit_tests/components/test_packmol.py
- openff/interchange/components/_packmol.py
> Log packing failures

- docs/using/edges.md
- openff/interchange/components/interchange.py
- openff/interchange/interop/common.py
- openff/interchange/interop/openmm/_positions.py
Resolves #1077, reversing one (important) default value in #1074 but not changing the overall design
> Export positions with virtual sites by default

- devtools/conda-envs/docs_env.yaml
- docs/conf.py
- docs/docutils.conf
- docs/installation.md
- docs/using/plugins.md
- openff/interchange/components/interchange.py
This PR updates Sphinx to a more recent version, as well as fixing a few rendering issues in the API docs. The main beneficial change here is that the API docs now have a right hand margin navigation menu, so users can quickly navigate to a field or function. Previously, this worked for modules but not classes.
I investigated updating further, but 6.2+ made changes to how privacy detection works that breaks our lazy loading subpackages. Curse Python for making modules and packages different!
I also investigated using a pre-commit hook to line wrap docstrings. I tried two formatters, [docformatter](https://github.com/PyCQA/docformatter) and [pydocstringformatter](https://github.com/DanielNoord/pydocstringformatter). Neither seemed to be able to reliably get docstrings to wrap to the …
> Update Sphinx to 6.1.2

- docs/releasehistory.md
- openff/interchange/interop/openmm/_import/_import.py
I missed this at some point in 0.4.0 testing; the decorator was removed from `Interchange.from_openmm` but not this (internal) call.
> Remove an extra `@experimental` decorator

- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/docs_env.yaml
- devtools/conda-envs/test_env.yaml
Something changed in regression tests, but not in a way I can reproduce locally
> Constrain `openmm =8.1.2` in tests

- .readthedocs.yml
- docs/conf.py
- pyproject.toml
RTD builds are succeeding, but with warnings that suggest that API docs are not being generated. I can't reproduce the issue locally so I'm going to poke around here.
> Fix RTD build

- docs/using/output.md
- examples/protein_ligand/protein_ligand.ipynb
- openff/interchange/_tests/_gromacs.py
- openff/interchange/_tests/conftest.py
- openff/interchange/_tests/interoperability_tests/gromacs/test_systems.py
- openff/interchange/components/interchange.py
- openff/interchange/drivers/gromacs.py
- openff/interchange/interop/gromacs/export/_export.py
Resolves #95
This is opt-in with a `monolithic=False` argument wired through various methods.
Currently, this splits out monolithic topology files into
* A single `f"{prefix}_atomtypes.itp` containing non-bonded parameters
* Currently this is just `[ atomtypes ]` and I don't see anything else in `$CONDA_PREFIX/share/gromacs/top/*.ff/ffnonbonded.itp` that indicates other directives conventionally go here
* A `f"{prefix}_{molecule_name}.itp` file for each unique molecule type, containing each molecule type's atom types, charges, valence parameters, constraints, virtual sites, etc.
* The molecule name is meant to be a canonicalized version of the `Molecule.name` attribute
I don't think this actually reduces the net file size on disk, barring sketchy force field re-use, but it does split it …
> Optionally write GROMACS topologies as multiple `.itp` files

- docs/releasehistory.md
- openff/interchange/_tests/unit_tests/interop/openmm/_import/test_import.py
- openff/interchange/interop/openmm/_import/_import.py
> Create blank collections when importing only water

- .github/workflows/ci.yaml
- docs/releasehistory.md
- docs/using/edges.md
- openff/interchange/_tests/interoperability_tests/test_openmm.py
- openff/interchange/_tests/unit_tests/interop/openmm/test_openmm.py
- openff/interchange/_tests/unit_tests/interop/test_openmm.py
- openff/interchange/components/interchange.py
- openff/interchange/interop/openmm/__init__.py
> Add center-of-mass motion remover in OpenMM export

- openff/interchange/components/_packmol.py
> Document why `tolerance` is removed from box edges

- .github/workflows/examples.yaml
- devtools/conda-envs/examples_env.yaml
- docs/using/edges.md
- openff/interchange/_tests/unit_tests/operations/test_combine.py
- openff/interchange/operations/_combine.py
> Error when non-bonded 1-4 scaling factors differ significantly

- devtools/conda-envs/docs_env.yaml
- openff/interchange/operations/_combine.py
The current warning message communicates that `Interchange.combine` is not suitable for production and marginally tested, neither of which is the case.
> Update `Interchange.combine` warning

- .github/workflows/beta.yaml
- .github/workflows/ci.yaml
- .github/workflows/examples.yaml
- devtools/conda-envs/docs_env.yaml
- docs/releasehistory.md
Applies to any release made on or after April 4, 2025.
Python 3.11 was released in October 2022 and anything that has not been updated is, in my judgement, de facto unmaintained.
https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table
> Drop Python 3.10

- docs/using/output.md
- openff/interchange/_tests/unit_tests/interop/lammps/export/test_lammps.py
- openff/interchange/components/interchange.py
- openff/interchange/interop/lammps/export/export.py
This adds the option to export the SMIRKs as LAMMPS type labels. For multi-term torsions, the multi index is appended to the SMIRKs.
This is implemeted through an optional flag in `to_lammps()`. For example: `interchange.to_lammps("out", include_type_labels=True)`.
This feature is necessary when combing files using external software where types are not consistent between files. For example, when using LAMMPS `fix bond/react` a user needs to create pre- and post-reaction templates with consistent atom/bond/etc types.
An example of the type labels that can be included in the LAMMPS data file are shown below for `OC=O`. See https://docs.lammps.org/Howto_type_labels.html for more information on LAMMPS type labels. Note that type labels were added in LAMMPS version `15Sep2022`.
I have been …
> LAMMPS type labels

- docs/releasehistory.md
- openff/interchange/_tests/unit_tests/operations/test_combine.py
- openff/interchange/operations/_combine.py
Resolves #1165. By default, `Interchange.combine` allows the vdW and Electrostatics cutoffs (and the switching distance) to differ by up to 1e-6 nm. The tolerance for 1-4 scaling is 1e-6 (unitless). These are not exposed to the user and I don't want them to change much, but I'm open to them being the wrong choices to start them out at.
> Allow `Interchange.combine` when cutoffs differ by tiny amount

- docs/releasehistory.md
Closes #1251 
Might want to include #1220, not planning to get #1252 in this release
Using https://github.com/openforcefield/openff-interchange/milestone/20
Using this as a double-check of merged PRs: https://github.com/openforcefield/openff-interchange/compare/v0.4.2...main
This is a similar report (I think these changes are all called out in release notes):
```shell
$ griffe check -a v0.4.2 -b HEAD openff.interchange
openff/interchange/components/interchange.py:906: Interchange.from_openmm(topology): Parameter is now required
openff/interchange/models.py:394: VirtualSiteKey: Public object points to a different kind of object: class -> attribute
openff/interchange/interop/gromacs/models/models.py:344: GROMACSSystem.molecules: Attribute value was changed: Field(dict(), description='The …
```
> Finalize release v0.4.3

- docs/releasehistory.md
- openff/interchange/plugins/__init__.py
See https://github.com/conda-forge/openff-interchange-feedstock/issues/99
> Remove `importlib_metadata` backport when loading plugins

- .pre-commit-config.yaml
- docs/releasehistory.md
- openff/interchange/_tests/unit_tests/components/test_packmol.py
- openff/interchange/components/_packmol.py
Fixes #1268 
This PR implements the SLTCAP method for adding ions to represent bulk salt in a system with a non-neutral solute.
To check my understanding, line 904 previously read
`    water_mass_to_add = solvent_mass - nacl_mass`
But this is the total mass of solvent molecules in the entire box minus the mass of one NaCl molecule. I think this line should have been
`    water_mass_to_add = solvent_mass - nacl_mass_to_add`
For consistency with the protein benchmark setup, I also changed the molarity of pure water from 55.5 M (value at 273 K) to 55.4 M (value at 293 K, closer to the temperature for most protein simulations). This probably won't change the number of ions in most systems, and I don't feel strongly about this change.
> Implement SLTCAP in `solvate_topology`
