openforcefield/openff-interchange

- .github/workflows/ci.yaml
- devtools/conda-envs/test_env.yaml
- system/tests/test_utils.py
- system/utils.py
Adding some functions
Notable points that this PR has either accomplished or will accomplish.
> Add some utils and tests

- devtools/conda-envs/test_env.yaml
- system/potential.py
- system/tests/base_test.py
- system/tests/test_potential.py
- system/utils.py
Minimal prototype of a `Potential` class mirroring `gmso.Potential` but built off of Pydantic.
Notable points that this PR has either accomplished or will accomplish.
> Potential class prototype

- .github/workflows/ci.yaml
Checking to see if mamba saves CI time
> MAINT: Use mamba with miniconda action

- openff/system/tests/base_test.py
- openff/system/tests/test_interop/test_parmed.py
- openff/system/tests/test_matrix_representations.py
- openff/system/tests/utils.py
In tests and prototyping, I've found myself often creating a single-molecule topology from SMILES
> Update tests with top_from_smiles

- examples/parameter_replacement.ipynb
- openff/system/components/smirnoff.py
This PR adds a minimal parameter replacement example
> Add parameter replacement example

- README.md
- environment.yml
- examples/README.md
- postBuild
This PR sets up the notebooks in the  `examples/` folder on https://mybinder.org/
This link might work: https://mybinder.org/v2/gh/openforcefield/openff-system/master?filepath=%2Fexamples%2F
> Set up binder

- examples/smirnoff_argon.ipynb
- examples/smirnoff_ethanol.ipynb
- openff/system/components/potentials.py
- openff/system/components/smirnoff.py
- openff/system/tests/test_potential.py
> Store "slot" identifiers as str

- openff/system/components/smirnoff.py
- openff/system/stubs.py
- openff/system/tests/base_test.py
- openff/system/tests/test_stubs.py
This PR implements support for SMIRNOFF-style constraints
> Support SMIRNOFF constraints

- openff/system/components/smirnoff.py
This PR changes the internal storage of proper torsions to a more matrix-friendly representation.
Resolves #63
> Separate multi-term torsions into separate Potential objects

- .github/workflows/lint.yaml
- openff/system/__init__.py
- openff/system/_version.py
- openff/system/components/potentials.py
- openff/system/components/smirnoff.py
- openff/system/stubs.py
- openff/system/tests/base_test.py
- openff/system/tests/integration_tests/test_interoperability_pathways.py
- openff/system/tests/test_external.py
- openff/system/tests/test_matrix_representations.py
- openff/system/tests/test_types.py
- openff/system/tests/test_typing.py
- openff/system/tests/test_utils.py
- openff/system/types.py
- openff/system/utils.py
This PR adds and satisfies some flake8 plugins to safeguard against some of my iffy/ugly programming tendencies.
> Add more flake8 linters

- openff/system/components/potentials.py
- openff/system/components/smirnoff.py
- openff/system/components/system.py
- openff/system/interop/internal.py
- openff/system/interop/openmm.py
- openff/system/interop/parmed.py
- openff/system/stubs.py
- openff/system/tests/integration_tests/test_interoperability_pathways.py
- openff/system/tests/test_interop/test_openmm.py
- openff/system/tests/test_interop/test_parmed.py
- openff/system/tests/test_potential.py
- openff/system/tests/test_types.py
- openff/system/types.py
- setup.cfg
This PR takes the model in #77 and implements it throughout this project.
Notable points that this PR has either accomplished or will accomplish.
> Implement unit model

- .github/workflows/ci.yaml
- examples/SMIRNOFF_simulation.ipynb
- examples/smirnoff_ethanol.ipynb
- openff/system/stubs.py
This PR updates the `SMIRNOFF_simulation.ipynb` example, which has been out of date for a few months. It also includes a small fix processing box vectors, which can possibly become a tuple.
> Update SMIRNOFF_simulation example

- README.md
- devtools/conda-envs/intermol_env.yaml
- devtools/conda-envs/test_env.yaml
- docs/releasehistory.rst
- openff/system/tests/test_utils.py
- openff/system/utils.py
This PR updates the README and cleans up some un-used code in anticipation of an early pre-release.
> Cleanup for 0.1.0 release

- .github/workflows/integration_tests.yaml
- devtools/conda-envs/intermol_env.yaml
- devtools/conda-envs/test_env.yaml
- examples/README.md
- examples/SMIRNOFF_simulation.ipynb
- examples/optimize-with-jax.ipynb
- examples/parameter_replacement.ipynb
- examples/smirnoff_argon.ipynb
- examples/smirnoff_ethanol.ipynb
- openff/system/components/potentials.py
- openff/system/components/smirnoff.py
- openff/system/components/system.py
- openff/system/exceptions.py
- openff/system/stubs.py
- openff/system/tests/base_test.py
- openff/system/tests/files/README.md
- openff/system/tests/integration_tests/test_interoperability_pathways.py
- openff/system/tests/test_external.py
- openff/system/tests/test_interop/test_internal_writers.py
- openff/system/tests/test_interop/test_openmm.py
- openff/system/tests/test_potential.py
- openff/system/tests/test_stubs.py
- openff/system/tests/test_utils.py
- openff/system/tests/utils.py
- openff/system/utils.py
- setup.cfg
This PR serves as the hub for updating to OpenFF Toolkit 0.9.0 and includes some reworking of logic pathways.
> Toolkit updates

- .codecov.yml
- .github/workflows/ci.yaml
- .github/workflows/lint.yaml
- README.md
I'm not sure what was causing the Python 3.9 block previously but my checker script doesn't find any missing dependencies locally. I'm holding off on dropping Python 3.6 until it causes issues, however minor.
> Update Python versions in test, README snippet

- openff/system/interop/internal.py
- openff/system/tests/energy_tests/gromacs.py
- openff/system/tests/energy_tests/openmm.py
- openff/system/tests/energy_tests/test_energies.py
This PR adds tests and supporting infrastructure to compare the energies of the same system evaluated by different engines.
> Add energy comparison tests

- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
This PR is a scattering of configuration updates
> Maintenance updates

- openff/system/components/system.py
- openff/system/interop/compatibility/nonbonded.py
- openff/system/tests/energy_tests/gromacs.py
- openff/system/tests/energy_tests/openmm.py
- openff/system/tests/energy_tests/test_energies.py
- openff/system/tests/energy_tests/utils.py
- openff/system/tests/test_interop/test_compatibility.py
This PR adds a small compatibility layer that can be built out once there is some progress on i.e. #103
> Add nonbonded method compatibility checks, fix energy tests

- .github/workflows/ci.yaml
- openff/system/components/smirnoff.py
- openff/system/interop/internal.py
- openff/system/interop/openmm.py
- openff/system/interop/parmed.py
- openff/system/stubs.py
- openff/system/tests/test_stubs.py
- openff/system/tests/utils.py
- setup.cfg
This PR is an experiment in overhauling the handling of electrostatics data.
> Overhaul electrostatics handling

- .pre-commit-config.yaml
- docs/developing.md
This PR adds developer documentation, mostly directions for satisfying the linters that run in CI.
@umesh-timalsina, @daico007, @justinGilmer - could you let me know if anything glaring is missing, anything that would have been useful to know a few days ago? An exhaustive review is not necessary, as this is a living document that I hope sees regular updates.
> Add developer docs

- openff/system/tests/test_types.py
- openff/system/types.py
This PR fixes an oversight from earlier. It is particularly useful for i.e. setting positions from files read by OpenMM
> Allow ArrayQuantity to be set with SimTK Quantity

- openff/system/interop/internal/lammps.py
- openff/system/tests/energy_tests/lammps.py
- openff/system/tests/energy_tests/test_energies.py
- openff/system/tests/test_interop/test_lammps.py
This PR is a follow-on to #125. I don't currently know what all it will include.
> Improvements to LAMMPS exporter

- openff/system/components/smirnoff.py
- openff/system/interop/openmm.py
- openff/system/interop/parmed.py
- openff/system/tests/energy_tests/test_energies.py
- openff/system/tests/integration_tests/test_interoperability_pathways.py
- openff/system/tests/test_interop/test_compatibility.py
- openff/system/tests/test_interop/test_internal_writers.py
- openff/system/tests/utils.py
I've picked up some bad habits around unit conversion and some of the internals were ugly and error-prone. This PR fixes those patterns.
> Use safer unit conversions

- .github/workflows/ci.yaml
- openff/system/components/potentials.py
- openff/system/exceptions.py
- openff/system/interop/openmm.py
- openff/system/tests/test_buckingham.py
- openff/system/tests/test_matrix_representations.py
- openff/system/tests/test_rb_torsions.py
- openff/system/tests/test_stubs.py
- openff/system/tests/test_utils.py
- openff/system/tests/utils.py
- openff/system/utils.py
- setup.cfg
Fewer copied LOC across projects. This is meant to be synced up with https://github.com/mattwthompson/openff-utilities/commit/f9a9ef6e40a0d4f4aa1783d520f1da26870721a1
> Move some functions to openff-utilities

- openff/system/interop/parmed.py
This PR makes `parmed` an optional dependency / import. Fixes #162
> Make `parmed` an optional import

- openff/system/components/mdtraj.py
- openff/system/components/smirnoff.py
- openff/system/tests/components/smirnoff.py
- openff/system/tests/test_interop/test_lammps.py
> Fix enumeration of SMIRNOFF trefoil impropers

- openff/system/components/foyer.py
- openff/system/components/smirnoff.py
- openff/system/components/system.py
- openff/system/interop/internal/gromacs.py
- openff/system/interop/openmm.py
- openff/system/interop/parmed.py
- openff/system/tests/test_interop/test_gromacs.py
- openff/system/tests/test_interop/test_openmm.py
I started this to try and resolve #178 but I guess I already did that last week (?). However, I didn't push those changes through to the exporters, which is what this does.
> Check mixing rule in some exporters

- openff/system/components/smirnoff.py
- openff/system/components/system.py
Implements the idea from https://github.com/openforcefield/openff-system/pull/200#issuecomment-853919970
Two major weak points are the convoluted constraints logic and messy electrostatics treatments; I'll fix the constraint logic later, and the electrostatics methods will be completely swapped out when this gets merged into #200. This method should be even slimmer once those changes are in place.
Everything passed locally, which is encouraging for what is a small refactor in a linchpin of this project. It might also point to corner cases that aren't yet covered in tests.
@SimonBoothroyd let me know if this is what you had in mind - the number of lines of code removed is a huge win in my book, especially given that the removed code was the messy result of several ideas I've tried over …
> Update System.from_smirnoff with dependency injection logic

- devtools/conda-envs/test_env.yaml
- openff/system/components/foyer.py
- openff/system/components/system.py
- openff/system/tests/components/test_foyer.py
- openff/system/tests/components/test_system.py
> Refactor from_foyer and use new foyer API

- openff/interchange/components/mdtraj.py
- openff/interchange/tests/components/test_mdtraj.py
> Fix double-counting of 1-4 pairs in rings

- openff/interchange/components/interchange.py
- openff/interchange/interop/openmm.py
- openff/interchange/tests/components/test_interchange.py
I found some behaviors that weren't explicitly tested and a few methods that should not currently be a part of the public API. This PR fixes that.
> Update some Interface API points and tests

- openff/interchange/drivers/openmm.py
- openff/interchange/exceptions.py
- openff/interchange/tests/__init__.py
- openff/interchange/tests/utils.py
That 86% test coverage is looking pretty iffy.
> Remove old code

- openff/interchange/components/smirnoff.py
- openff/interchange/tests/components/test_smirnoff.py
Resolves #251, mostly by porting toolkit code
> Catch unassigned valence parameters

- openff/interchange/models.py
- openff/interchange/tests/test_models.py
> Add optional fields to XKey hash methods

- .pre-commit-config.yaml
- examples/packed_box.ipynb
tl;dr shows how to morph a PDB file and a list of OpenFF Molecules into whatever you want
> Packed box example

- setup.cfg
Inspired by https://nedbatchelder.com/blog/201908/dont_omit_tests_from_coverage.html
> Do not omit tests from coverage

- .github/workflows/ci.yaml
- devtools/conda-envs/minimal_env.yaml
- devtools/conda-envs/test_env.yaml
- openff/interchange/components/mbuild.py
- openff/interchange/components/smirnoff.py
- openff/interchange/drivers/amber.py
- openff/interchange/drivers/lammps.py
- openff/interchange/drivers/openmm.py
- openff/interchange/energy_tests/components/tests_smirnoff.py
- openff/interchange/energy_tests/test_energies.py
- openff/interchange/energy_tests/test_toolkit.py
- openff/interchange/interop/internal/gromacs.py
- openff/interchange/interop/openmm.py
- openff/interchange/interoperability_tests/internal/test_gromacs.py
- openff/interchange/interoperability_tests/internal/test_lammps.py
- openff/interchange/interoperability_tests/test_external.py
- openff/interchange/interoperability_tests/test_interoperability_pathways.py
- openff/interchange/interoperability_tests/test_openmm.py
- openff/interchange/interoperability_tests/test_parmed.py
- openff/interchange/testing/utils.py
- openff/interchange/types.py
- openff/interchange/unit_tests/components/test_foyer.py
- openff/interchange/unit_tests/components/test_mbuild.py
- openff/interchange/unit_tests/components/test_mdtraj.py
- openff/interchange/unit_tests/components/test_smirnoff.py
- openff/interchange/unit_tests/test_types.py
- openff/interchange/unit_tests/test_utils.py
- openff/interchange/utils.py
- setup.cfg
> Updates for OpenMM 7.6

- .pre-commit-config.yaml
Same as https://github.com/openforcefield/openff-toolkit/pull/1064
> Replace nbqa-black with black-jupyter

- openff/interchange/unit_tests/components/test_smirnoff.py
> Port more toolkit tests

- openff/interchange/components/interchange.py
- openff/interchange/components/mdtraj.py
- openff/interchange/unit_tests/components/test_interchange.py
- openff/interchange/unit_tests/components/test_mdtraj.py
- stubs/mdtraj/__init__.pyi
> Avoid parameter clashes after combination

- openff/interchange/drivers/amber.py
- openff/interchange/interop/internal/amber.py
This is for https://github.com/openforcefield/openff-toolkit/pull/1113
> Fixes for toolkit example

- openff/interchange/components/interchange.py
- openff/interchange/interop/external.py
> Fix typos in docstrings

- openff/interchange/components/interchange.py
- openff/interchange/interop/openmm.py
- openff/interchange/interoperability_tests/test_openmm.py
> Add `Interchange.to_pdb`

- .github/workflows/ci.yaml
You will need to quote the python version when you add python 3.10 eventually
> fix issue with python 3.10

- docs/releasehistory.md
- openff/interchange/interoperability_tests/test_openmm.py
I would like a new toolkit release before pulling the trigger on this in case there are subtle incompatibilities.
> Draft 0.1.4 release notes

- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/docs_env.yaml
- devtools/conda-envs/minimal_env.yaml
- devtools/conda-envs/test_env.yaml
- openff/interchange/components/mbuild.py
- openff/interchange/interop/internal/amber.py
- openff/interchange/interop/internal/gromacs.py
- openff/interchange/interop/internal/lammps.py
- openff/interchange/interop/openmm.py
- openff/interchange/interop/parmed.py
https://github.com/openforcefield/openff-toolkit/pull/1182
> Update for toolkit elements refactor

- openff/interchange/interop/openmm.py
I found this while working on regression tests - [this](https://github.com/mattwthompson/interchange-regression-testing/blob/cb1379fc6092adb777b09e00c2e19370633373fc/value-propagation/test_modifications.py#L69-L95) or some subset should be merged into here at some point.
> Ensure switching function is applied with split nonbonded forces

- .github/workflows/ci.yaml
- .github/workflows/ci_minimal.yaml
- openff/interchange/tests/energy_tests/test_energies.py
I thought I included this in #404 but it seems I did not.
> Trim some long tests

- openff/interchange/components/interchange.py
- openff/interchange/components/smirnoff.py
- openff/interchange/tests/unit_tests/components/test_smirnoff.py
> Implement `charge_from_molecules` in `Interchange.from_smirnoff`

- openff/interchange/components/interchange.py
- openff/interchange/components/smirnoff.py
- openff/interchange/tests/unit_tests/components/test_smirnoff.py
> Implement `partial_bond_orders_from_molecules`

- .pre-commit-config.yaml
- setup.cfg
I typically forget to add `__init__.py` files, this should safeguard against that.
> Add flake8-no-pep420

- CITATION.cff
Add Vandy folks to `citation.ff`.
> add vandy folks to citation.ff

- CITATION.cff
Adding my name to CITATION.cff per @mattwthompson's suggestion in #424
> Add Joshua A. Mitchell to CITATION.cff

- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/test_env.yaml
- openff/interchange/drivers/gromacs.py
- openff/interchange/interop/openmm.py
- openff/interchange/tests/__init__.py
- openff/interchange/tests/interoperability_tests/test_openmm.py
> Fix switching function not properly being applied in OpenMM export

- openff/interchange/components/smirnoff.py
Coordination with https://github.com/openforcefield/openff-toolkit/pull/1316
> Copy more parametrization internals from toolkit

- openff/interchange/interop/openmm.py
- openff/interchange/tests/interoperability_tests/test_openmm.py
- openff/interchange/tests/unit_tests/components/test_smirnoff.py
> Avoid creating OpenMM forces with no parameters

- openff/interchange/interop/openmm.py
> Do not use a tuple of elements in place of an element

- openff/interchange/tests/interoperability_tests/internal/test_gromacs.py
> Update tests for residue information in GROMACS exports

- .github/workflows/ci.yaml
It's supposed to be faster and appears to be close to a drop-in replacement
> Use micromamba in CI

- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/docs_env.yaml
- devtools/conda-envs/examples_env.yaml
- devtools/conda-envs/test_env.yaml
- environment.yml
- openff/interchange/components/_particles.py
- openff/interchange/interop/openmm/__init__.py
- openff/interchange/interop/openmm/_nonbonded.py
- openff/interchange/interop/openmm/_valence.py
- openff/interchange/interop/openmm/_virtual_sites.py
- openff/interchange/tests/energy_tests/test_toolkit.py
- openff/interchange/tests/interoperability_tests/test_openmm.py
- openff/interchange/tests/unit_tests/components/test_smirnoff.py
- setup.cfg
> Update virtual sites in OpenMM export

- openff/interchange/interop/openmm/__init__.py
- openff/interchange/interop/openmm/_nonbonded.py
- openff/interchange/interop/openmm/_valence.py
- openff/interchange/tests/interoperability_tests/test_openmm.py
- openff/interchange/tests/unit_tests/interop/test_openmm.py
> Fix atom indexing in valence terms when virtual sites are present

- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/docs_env.yaml
- openff/interchange/components/smirnoff.py
> Fix docs builds and remove a deprecated call

- docs/releasehistory.md
> Add v0.2.2 release notes

- .github/workflows/ci.yaml
- devtools/conda-envs/docs_env.yaml
- devtools/conda-envs/test_env.yaml
I broke something esoteric in the toolkit, this is a workaround.
> Do not install OpenEye Toolkits when it will not be licensed

- docs/releasehistory.md
This PR fleshes out the release notes for the 0.2.3 release notes.
> Add v0.2.3 release notes

- .github/workflows/beta.yaml
- .github/workflows/ci.yaml
- .github/workflows/ci_minimal.yaml
- .github/workflows/examples.yaml
See i.e. https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
> Do not call `setup.py` directly

- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/docs_env.yaml
- devtools/conda-envs/examples_env.yaml
- devtools/conda-envs/test_env.yaml
- openff/interchange/components/potentials.py
- openff/interchange/tests/unit_tests/components/test_smirnoff.py
> Update for JAX 0.4

- .github/workflows/ci.yaml
- .github/workflows/ci_minimal.yaml
- .github/workflows/examples.yaml
- .pre-commit-config.yaml
- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/examples_env.yaml
- devtools/conda-envs/test_env.yaml
- docs/index.md
- docs/using/plugins.md
- openff/interchange/plugins/__init__.py
- openff/interchange/smirnoff/_create.py
- openff/interchange/tests/data/buckingham.offxml
- openff/interchange/tests/unit_tests/plugins/__init__.py
- openff/interchange/tests/unit_tests/plugins/test_smirnoff_plugins.py
- openff/interchange/tests/unit_tests/smirnoff/test_create.py
- plugins/nonbonded_plugins.py
- plugins/setup.py
- setup.cfg
> Support custom SMIRNOFF handlers

- devtools/conda-envs/dev_env.yaml
- docs/releasehistory.md
- openff/interchange/interop/openmm/_valence.py
- openff/interchange/smirnoff/_base.py
- openff/interchange/smirnoff/_nonbonded.py
- openff/interchange/smirnoff/_valence.py
- openff/interchange/tests/unit_tests/smirnoff/test_valence.py
- setup.cfg
> Store potential parameters at class level

- docs/releasehistory.md
- openff/interchange/interop/openmm/_nonbonded.py
- openff/interchange/tests/unit_tests/interop/test_openmm.py
Closes #592, helps with #591 
These changes
> Improve logic in OpenMM export when no vdW handler exists

- devtools/conda-envs/test_env.yaml
- docs/releasehistory.md
- openff/interchange/components/potentials.py
- openff/interchange/exceptions.py
- openff/interchange/interop/openmm/__init__.py
- openff/interchange/interop/openmm/_nonbonded.py
- openff/interchange/smirnoff/_base.py
- openff/interchange/tests/interoperability_tests/test_openmm.py
- openff/interchange/tests/unit_tests/plugins/test_smirnoff_plugins.py
- plugins/nonbonded_plugins.py
- plugins/setup.py
> Support double exponential force fields

- openff/interchange/interop/internal/amber.py
- openff/interchange/tests/interoperability_tests/internal/test_amber.py
> Fix Amber residue names in single-residue systems

- docs/using/output.md
> Add more information about OpenMM conversions

- docs/releasehistory.md
- openff/interchange/interop/openmm/__init__.py
- openff/interchange/interop/openmm/_gbsa.py
- openff/interchange/interop/openmm/_nonbonded.py
- openff/interchange/smirnoff/_create.py
- openff/interchange/smirnoff/_gbsa.py
- openff/interchange/tests/data/gbsa.offxml
- openff/interchange/tests/interoperability_tests/test_openmm.py
- openff/interchange/tests/unit_tests/smirnoff/test_gbsa.py
- setup.cfg
This PR adds `SMIRNOFFGBSACollection` and its associated method creating an OpenMM force.
> Support SMIRNOFF GBSA parameters

- openff/interchange/interop/openmm/__init__.py
- openff/interchange/interop/openmm/_nonbonded.py
- openff/interchange/smirnoff/_base.py
- plugins/nonbonded_plugins/nonbonded.py
- plugins/setup.py
> Support SMIRNOFF plugins modifying OpenMM objects without boostrapping

- docs/releasehistory.md
- examples/ligand_in_water/ligand_in_water.ipynb
- openff/interchange/interop/openmm/_positions.py
- openff/interchange/tests/interoperability_tests/test_openmm.py
> Fix `to_openmm_positions`

- openff/interchange/smirnoff/_nonbonded.py
In https://github.com/openforcefield/smirnoff-plugins/pull/53#discussion_r1139052589 we discovered that two `create_virtual_sites` methods were not used.
> Remove old virtual site construction methods

- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/examples_env.yaml
- devtools/conda-envs/test_env.yaml
- openff/interchange/components/mdconfig.py
- openff/interchange/drivers/lammps.py
- openff/interchange/tests/unit_tests/drivers/test_all.py
This PR attempts to re-introduce energy tests using LAMMPS. Previously, it was removed due to packaging issues.
> Bring LAMMPS driver back online

- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/examples_env.yaml
- devtools/conda-envs/test_env.yaml
- openff/interchange/components/mdconfig.py
- openff/interchange/drivers/lammps.py
- openff/interchange/tests/unit_tests/drivers/test_all.py
- openff/interchange/tests/unit_tests/drivers/test_lammps.py
> Refactor LAMMPS energy reporting

- openff/interchange/drivers/gromacs.py
- openff/interchange/exceptions.py
- openff/interchange/tests/energy_tests/test_energies.py
- openff/interchange/tests/unit_tests/components/test_foyer.py
> Refactor GROMACS energy reporting

- openff/interchange/drivers/amber.py
> Refactor Amber energy reporting

- docs/_templates/autosummary/base.rst
- docs/_templates/autosummary/class.rst
- docs/_templates/autosummary/module.rst
- docs/conf.py
- docs/using/plugins.md
- openff/interchange/plugins/__init__.py
The current documentation and examples for plugins in `v0.3.0beta4` could use some improvement.
https://docs.openforcefield.org/projects/interchange/en/latest/using/plugins.html
> Improve plugin docs

- openff/interchange/smirnoff/_gromacs.py
- openff/interchange/tests/unit_tests/components/test_foyer.py
- openff/interchange/tests/unit_tests/interop/gromacs/export/__init__.py
- openff/interchange/tests/unit_tests/interop/gromacs/export/test_export.py
- openff/interchange/tests/unit_tests/smirnoff/test_gromacs.py
> Ensure residue names are set from SMIRNOFF to GRO files

- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/test_env.yaml
- docs/releasehistory.md
- openff/interchange/drivers/gromacs.py
- openff/interchange/tests/__init__.py
- openff/interchange/tests/interoperability_tests/internal/test_gromacs.py
- openff/interchange/tests/interoperability_tests/test_external.py
- openff/interchange/tests/unit_tests/components/test_foyer.py
> Remove use of `pkg_resources`

- docs/releasehistory.md
- examples/experimental/openmm-import/protein-ligand.ipynb
- examples/protein_ligand/protein_ligand.ipynb
- openff/interchange/common/__init__.py
- openff/interchange/common/_nonbonded.py
- openff/interchange/common/_valence.py
- openff/interchange/interop/openmm/__init__.py
- openff/interchange/interop/openmm/_import/_import.py
- openff/interchange/interop/openmm/_nonbonded.py
- openff/interchange/interop/openmm/export/__init__.py
- openff/interchange/smirnoff/_nonbonded.py
- openff/interchange/tests/__init__.py
> Create module for base `Collection` classes

- openff/interchange/tests/unit_tests/drivers/test_all.py
One cause of #638 is that something is not right with some of the drivers (Amber, LAMMPS) if bonds are constrained. Related #632 #470
> Use constrained force field when testing energy reporters

- docs/releasehistory.md
- openff/interchange/interop/internal/amber.py
- openff/interchange/tests/interoperability_tests/internal/test_amber.py
This is a minimal band-aid for #652
> Attempt to always write RESIDUE_LABEL

- docs/releasehistory.md
- openff/interchange/__init__.py
- openff/interchange/_tests/__init__.py
- openff/interchange/_tests/unit_tests/smirnoff/test_create.py
- openff/interchange/_tests/unit_tests/smirnoff/test_gromacs.py
- openff/interchange/_version.py
- openff/interchange/smirnoff/_gromacs.py
- openff/interchange/smirnoff/_valence.py
> Write `[ settles ]`

- .github/workflows/changes.yaml
https://mkdocstrings.github.io/griffe/checking/#detected-breakages
> Automatically detect API changes

- .github/workflows/changes.yaml
- docs/releasehistory.md
- openff/interchange/_tests/unit_tests/interop/gromacs/models/test_models.py
- openff/interchange/components/interchange.py
- openff/interchange/interop/gromacs/models/models.py
> Simplify wrapping GROMACS exporters

- docs/releasehistory.md
- openff/interchange/_tests/data/lig_CHEMBL3265016-1.pdb
- openff/interchange/_tests/unit_tests/interop/amber/export/test_export.py
- openff/interchange/interop/amber/export/_export.py
> Fix text wrapping and exclusions in Amber export

- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/docs_env.yaml
- devtools/conda-envs/examples_env.yaml
- devtools/conda-envs/minimal_env.yaml
- devtools/conda-envs/test_env.yaml
- openff/interchange/_tests/unit_tests/components/test_toolkit.py
> Test topology isomorphism with simple molecules

- .github/workflows/beta.yaml
- .github/workflows/ci.yaml
- .github/workflows/ci_minimal.yaml
- .github/workflows/examples.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/examples_env.yaml
- devtools/conda-envs/minimal_env.yaml
- devtools/conda-envs/test_env.yaml
- examples/experimental/openmmforcefields.ipynb
- openff/interchange/_tests/unit_tests/interop/amber/export/test_export.py
- openff/interchange/drivers/all.py
- openff/interchange/drivers/openmm.py
- openff/interchange/interop/amber/export/_export.py
> Fix non-bonded interactions in Amber export

- openff/interchange/_tests/unit_tests/interop/openmm/_import/test_import.py
- openff/interchange/components/interchange.py
- openff/interchange/drivers/all.py
- openff/interchange/interop/openmm/_import/_import.py
- stubs/mdtraj/core/residue_names.pyi
> Store constraints in `from_openmm`

- devtools/conda-envs/examples_env.yaml
- examples/vectorized_representations/vectorized_representations.ipynb
This PR splits off what was previously part of a larger example that is no longer supported.
> Add vectorized representation example

- .github/workflows/examples.yaml
- examples/packed_box/packed_box.ipynb
- examples/protein_ligand/protein_ligand.ipynb
- openff/interchange/_tests/unit_tests/components/test_packmol.py
- openff/interchange/components/_packmol.py
- openff/interchange/drivers/all.py
- stubs/mdtraj/__init__.pyi
> Update solvent example

- openff/interchange/interop/openmm/_nonbonded.py
> Fix setting vdW 1-4 scaling factor in OpenMM export

- docs/releasehistory.md
- openff/interchange/__init__.py
> Remove unnecessary import

- docs/index.md
- docs/using/experimental.md
- openff/interchange/_tests/unit_tests/components/test_interchange.py
- openff/interchange/components/interchange.py
- openff/interchange/interop/gromacs/_import/_import.py
> Make experimental features public

- examples/protein_ligand/protein_ligand.ipynb
- openff/interchange/_tests/unit_tests/components/test_mdconfig.py
- openff/interchange/_tests/unit_tests/components/test_packmol.py
- openff/interchange/_tests/unit_tests/smirnoff/test_nonbonded.py
- openff/interchange/common/_nonbonded.py
- openff/interchange/components/_packmol.py
- openff/interchange/components/interchange.py
- openff/interchange/components/mdconfig.py
- openff/interchange/drivers/gromacs.py
- openff/interchange/interop/openmm/_nonbonded.py
- openff/interchange/smirnoff/_nonbonded.py
This PR updates the protein-ligand example, including
* Directly loading multicomponent PDB files into the toolkit - absolutely fantastic work @j-wags, this is a dream to use
* Updating the PACKMOL wrapper to process a `Topology` instead of a PDB file - sorry @Yoshanuikabundi, I see now why you made this change; sometimes I just have to learn through firsthand pain
> Update protein-ligand example

- openff/interchange/_tests/unit_tests/components/test_mdconfig.py
- openff/interchange/components/mdconfig.py
Resolves #710 and possibly other things.
> Update auto-generated `sander` input script

- docs/releasehistory.md
- openff/interchange/_tests/unit_tests/interop/gromacs/export/test_export.py
- openff/interchange/interop/gromacs/export/_export.py
> Ensure `[ settles ]` are written in nanometers

- docs/releasehistory.md
- openff/interchange/_tests/test_issues.py
- openff/interchange/interop/gromacs/export/_export.py
> Fix some formatting issues in GROMACS files

- .github/workflows/beta.yaml
- .github/workflows/ci.yaml
- .github/workflows/ci_minimal.yaml
- .github/workflows/examples.yaml
> Switch to `setup-micromamba`

- docs/releasehistory.md
- openff/interchange/_tests/unit_tests/components/test_interchange.py
- openff/interchange/_tests/unit_tests/components/test_potentials.py
- openff/interchange/common/_nonbonded.py
- openff/interchange/components/interchange.py
- openff/interchange/components/potentials.py
- openff/interchange/foyer/_nonbonded.py
- openff/interchange/smirnoff/_base.py
- openff/interchange/smirnoff/_nonbonded.py
This PR fixes `Interchange` JSON deserialization, does the same for some components, and adds tests for some roundtrips.
> Add JSON roundtrips

- .github/workflows/beta.yaml
- .github/workflows/ci.yaml
- .github/workflows/ci_minimal.yaml
- .github/workflows/examples.yaml
- devtools/conda-envs/test_env.yaml
- openff/interchange/_tests/__init__.py
- openff/interchange/_tests/interoperability_tests/internal/test_amber.py
- openff/interchange/_tests/unit_tests/drivers/test_all.py
#750 but trying to work around an unreported GitHub outage
> Test on Python 3.11

- devtools/conda-envs/minimal_env.yaml
- openff/interchange/_tests/__init__.py
- openff/interchange/_tests/energy_tests/components/tests_smirnoff.py
- openff/interchange/_tests/interoperability_tests/internal/test_amber.py
- openff/interchange/_tests/interoperability_tests/test_openmm.py
- openff/interchange/_tests/unit_tests/interop/amber/export/test_export.py
- openff/interchange/_tests/unit_tests/interop/openmm/_import/test_import.py
- openff/interchange/_tests/unit_tests/interop/test_openmm.py
- openff/interchange/_tests/unit_tests/smirnoff/test_create.py
- openff/interchange/_tests/unit_tests/smirnoff/test_valence.py
- openff/interchange/_tests/unit_tests/smirnoff/test_virtual_sites.py
> Use `openff.toolkit._tests`

- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/docs_env.yaml
- devtools/conda-envs/examples_env.yaml
- devtools/conda-envs/minimal_env.yaml
- devtools/conda-envs/test_env.yaml
- openff/interchange/_tests/energy_tests/test_energies.py
- openff/interchange/_tests/interoperability_tests/test_openmm.py
- openff/interchange/interop/openmm/_nonbonded.py
- regression_tests/toolkit-to-interchange.json
A new version of the toolkit with some API breaks is released.
> Use OpenFF Toolkit 0.14.0+

- .pre-commit-config.yaml
- openff/interchange/_tests/unit_tests/components/test_interchange.py
- openff/interchange/_tests/unit_tests/interop/test_virtual_sites.py
- openff/interchange/components/interchange.py
- openff/interchange/exceptions.py
- openff/interchange/interop/_virtual_sites.py
- openff/interchange/interop/openmm/__init__.py
- openff/interchange/interop/openmm/_positions.py
Partially resolves https://github.com/openforcefield/openff-interchange/issues/478
> Refactor OpenMM positions export to common module

- docs/releasehistory.md
- openff/interchange/components/interchange.py
> Make `Interchange.from_openmm` a class method

- .github/workflows/ci.yaml
- openff/interchange/_tests/interoperability_tests/internal/test_amber.py
- openff/interchange/_tests/interoperability_tests/internal/test_gromacs.py
- openff/interchange/_tests/interoperability_tests/test_openmm.py
- openff/interchange/_tests/unit_tests/components/test_interchange.py
- openff/interchange/_tests/unit_tests/components/test_packmol.py
- openff/interchange/components/_packmol.py
Resolves #794 as discussed there.
> Use MDTraj to load PDB files with non-integer serial

- .github/workflows/ci.yaml
- devtools/conda-envs/dev_env.yaml
- docs/releasehistory.md
- openff/interchange/_tests/unit_tests/smirnoff/test_virtual_sites.py
- openff/interchange/common/_nonbonded.py
- openff/interchange/components/interchange.py
- openff/interchange/foyer/_nonbonded.py
- openff/interchange/interop/openmm/_import/_import.py
- openff/interchange/interop/openmm/_import/_nonbonded.py
- openff/interchange/interop/openmm/_nonbonded.py
- openff/interchange/smirnoff/_nonbonded.py
> Properly apply charges from virtual sites

- docs/releasehistory.md
- openff/interchange/smirnoff/_nonbonded.py
> Fix typos in the `vdWHandler` down-conversion warning

- .github/workflows/ci.yaml
- docs/releasehistory.md
- openff/interchange/_tests/conftest.py
- openff/interchange/_tests/unit_tests/interop/gromacs/export/test_export.py
- openff/interchange/_tests/unit_tests/interop/gromacs/export/test_virtual_sites.py
- openff/interchange/_tests/unit_tests/interop/gromacs/models/test_models.py
- openff/interchange/foyer/_nonbonded.py
- openff/interchange/interop/common.py
- openff/interchange/interop/gromacs/_import/_import.py
- openff/interchange/interop/gromacs/export/_export.py
- openff/interchange/interop/gromacs/export/_virtual_sites.py
- openff/interchange/interop/gromacs/models/models.py
- openff/interchange/interop/openmm/_nonbonded.py
- openff/interchange/smirnoff/_gromacs.py
> Add support for virtual sites in GROMACS

- docs/releasehistory.md
- openff/interchange/_tests/unit_tests/smirnoff/test_nonbonded.py
- openff/interchange/common/_nonbonded.py
- openff/interchange/components/_base.py
- openff/interchange/components/nonbonded.py
- openff/interchange/smirnoff/_nonbonded.py
> Track `scale12` from toolkit

- docs/releasehistory.md
- openff/interchange/_tests/interoperability_tests/internal/test_gromacs.py
- openff/interchange/_tests/unit_tests/interop/test_virtual_sites.py
- openff/interchange/_tests/unit_tests/smirnoff/test_base.py
- openff/interchange/_tests/unit_tests/smirnoff/test_create.py
- openff/interchange/components/interchange.py
- openff/interchange/interop/common.py
- openff/interchange/plugins/__init__.py
- openff/interchange/smirnoff/__init__.py
- setup.cfg
> Publicize SMIRNOFF collections

- .pre-commit-config.yaml
- docs/releasehistory.md
- examples/ligand_in_water/ligand_in_water.ipynb
> Fix water visualization in example

- .github/workflows/ci.yaml
> Fix rdtscp errors

- .github/workflows/ci.yaml
- devtools/conda-envs/dev_env.yaml
- openff/interchange/_tests/interoperability_tests/test_openmm.py
- openff/interchange/interop/common.py
- openff/interchange/interop/openmm/_nonbonded.py
- openff/interchange/smirnoff/_gromacs.py
- setup.cfg
> Fix virtual site indexing in OpenMM

- .github/workflows/examples.yaml
- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/docs_env.yaml
- devtools/conda-envs/examples_env.yaml
- devtools/conda-envs/test_env.yaml
- openff/interchange/components/interchange.py
> Assorted updates

- docs/releasehistory.md
- openff/interchange/_tests/unit_tests/interop/openmm/test_virtual_sites.py
- openff/interchange/_tests/unit_tests/smirnoff/test_virtual_sites.py
- openff/interchange/models.py
- openff/interchange/smirnoff/_virtual_sites.py
> Store virtual site type on `PotentialKeys`

- .github/workflows/ci.yaml
- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/docs_env.yaml
- devtools/conda-envs/examples_env.yaml
- devtools/conda-envs/test_env.yaml
- openff/interchange/_tests/data/README.md
- openff/interchange/_tests/data/de-force-1.0.1.offxml
- openff/interchange/_tests/interoperability_tests/test_openmm.py
- openff/interchange/_tests/unit_tests/plugins/test_smirnoff_plugins.py
- openff/interchange/common/_nonbonded.py
- openff/interchange/foyer/_nonbonded.py
Release 0.12.1 introduced Pydantic 2 compatibility, which allows Foyer to be re-introduced into the test suite.
> Re-introduce compatible Foyer, vendor double exponential force field

- .github/workflows/ci.yaml
- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/examples_env.yaml
- openff/interchange/_tests/interoperability_tests/test_openmm.py
- openff/interchange/_tests/unit_tests/smirnoff/test_valence.py
> Re-compute some reference results with new OEChem

- openff/interchange/_tests/interoperability_tests/test_openmm.py
- openff/interchange/components/toolkit.py
> Preserve OpenMM Topology hierarchy info in Interchange.from_openmm

- docs/releasehistory.md
- docs/using/status.md
- openff/interchange/_tests/unit_tests/interop/gromacs/export/test_hmr.py
- openff/interchange/_tests/unit_tests/interop/openmm/test_hmr.py
- openff/interchange/components/interchange.py
- openff/interchange/interop/openmm/__init__.py
- openff/interchange/smirnoff/_gromacs.py
> Add partial HMR implementation to GROMACS export

- devtools/conda-envs/examples_env.yaml
- examples/host-guest/host_guest.ipynb
- openff/interchange/_tests/conftest.py
- openff/interchange/_tests/unit_tests/interop/openmm/_import/test_import.py
- openff/interchange/components/interchange.py
- openff/interchange/interop/openmm/_import/_import.py
> Improvements to `Interchange.from_openmm`

- openff/interchange/_tests/__init__.py
- openff/interchange/_tests/unit_tests/drivers/test_all.py
- openff/interchange/drivers/lammps.py
Thanks to @timbernat for the suggestion
> Use LAMMPS's Python API in energy driver

- docs/releasehistory.md
- openff/interchange/_tests/energy_tests/smirnoff/__init__.py
- openff/interchange/_tests/energy_tests/smirnoff/test_base.py
- openff/interchange/_tests/unit_tests/smirnoff/test_base.py
- openff/interchange/smirnoff/_base.py
Resolves #908, at least in part
> Do not ignore float/int in JSON input

- openff/interchange/smirnoff/_base.py
This is resolving a small comment in #909
> Extended accepted types in collection loader

- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/test_env.yaml
- openff/interchange/_tests/unit_tests/interop/amber/export/test_export.py
- setup.cfg
(We weren't using it much, anyway)
> Remove MDAnalysis

- .pre-commit-config.yaml
- openff/interchange/_tests/__init__.py
- openff/interchange/_tests/conftest.py
- openff/interchange/_tests/unit_tests/common/test_positions.py
Context https://docs.astral.sh/ruff/rules/numpy-legacy-random/#numpy-legacy-random-npy002
> Use NumPy 2.0's recommended random number generator

- .github/workflows/ci.yaml
- .github/workflows/examples.yaml
- devtools/conda-envs/examples_env.yaml
- docs/releasehistory.md
- openff/interchange/_tests/unit_tests/components/test_interchange.py
- openff/interchange/_tests/unit_tests/operations/test_combine.py
- openff/interchange/components/interchange.py
- openff/interchange/components/mdconfig.py
- openff/interchange/exceptions.py
- openff/interchange/operations/_combine.py
- setup.cfg
> Error out when combining mismatched non-bonded settings

- examples/experimental/openmmforcefields/gaff.ipynb
I don't know why the energies differ so much on different hardware. And I'm not going to try to find out why.
#941
> Fix GAFF example

- docs/releasehistory.md
- openff/interchange/_tests/conftest.py
- openff/interchange/_tests/unit_tests/components/test_toolkit.py
- openff/interchange/_tests/unit_tests/smirnoff/test_virtual_sites.py
- openff/interchange/components/toolkit.py
- openff/interchange/smirnoff/_virtual_sites.py
- setup.cfg
> Do not use toolkit to look up virtual site parameters

- .github/workflows/beta.yaml
- .github/workflows/ci.yaml
- .github/workflows/examples.yaml
- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/examples_env.yaml
- devtools/conda-envs/test_env.yaml
Isolating this change from other work in case it's more complicated
> Use x64 macOS runners

- docs/releasehistory.md
- openff/interchange/_tests/unit_tests/interop/gromacs/_import/test_interchange.py
- openff/interchange/_tests/unit_tests/interop/gromacs/export/test_export.py
- openff/interchange/components/interchange.py
- openff/interchange/interop/gromacs/_interchange.py
- openff/interchange/operations/_combine.py
> Fix parsing GROMACS dihedrals

- devtools/conda-envs/test_env.yaml
- openff/interchange/_tests/unit_tests/interop/openmm/test_virtual_sites.py
- openff/interchange/interop/openmm/_nonbonded.py
- openff/interchange/smirnoff/_base.py
- openff/interchange/smirnoff/_create.py
> Set vdW parameters on virtual sites

- devtools/conda-envs/beta_env.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/examples_env.yaml
- devtools/conda-envs/test_env.yaml
- examples/ligand_in_water/ligand_in_water.ipynb
- openff/interchange/_tests/unit_tests/interop/gromacs/export/test_virtual_sites.py
- openff/interchange/_tests/unit_tests/interop/openmm/test_virtual_sites.py
- openff/interchange/_tests/unit_tests/interop/test_virtual_sites.py
- openff/interchange/_tests/unit_tests/smirnoff/test_virtual_sites.py
https://github.com/openforcefield/openff-toolkit/issues/1893
> Update tests for virtual site parameter lookup change

- openff/interchange/_tests/unit_tests/components/test_interchange.py
- openff/interchange/_tests/unit_tests/interop/openmm/_import/test_import.py
- openff/interchange/_tests/unit_tests/operations/test_combine.py
- openff/interchange/components/interchange.py
- openff/interchange/foyer/_create.py
- openff/interchange/interop/gromacs/_interchange.py
- openff/interchange/interop/openmm/_import/_import.py
- openff/interchange/smirnoff/_create.py
https://github.com/openforcefield/openff-interchange/issues/994
> Make `Interchange.topology` a required field

- .github/workflows/ci.yaml
- devtools/conda-envs/examples_env.yaml
Some builds of 2024.1.1 are broken
> Do not install broken OpenEye Toolkits package

- docs/releasehistory.md
Not much has happened since the last release, but it's been long enough.
> Finalize 0.3.28 release notes

- openff/interchange/_tests/unit_tests/drivers/test_all.py
- openff/interchange/smirnoff/_gromacs.py
> Improve speed of writing large molecules to GROMACS

- examples/ligand_in_water/.gitignore
- openff/interchange/smirnoff/_gromacs.py
Context https://github.com/openforcefield/openff-interchange/issues/1014#issuecomment-2251451736
> Improve GROMACS export performance in special case

- .pre-commit-config.yaml
- devtools/conda-envs/dev_env.yaml
- docs/using/output.md
- examples/amber/.gitignore
- examples/amber/amber.ipynb
- openff/interchange/_tests/unit_tests/components/test_interchange.py
- openff/interchange/components/interchange.py
Revives #440 based off of #1041
> Add amber example

- docs/releasehistory.md
- openff/interchange/_annotations.py
- openff/interchange/_tests/unit_tests/interop/openmm/test_hmr.py
- openff/interchange/components/interchange.py
- openff/interchange/exceptions.py
- openff/interchange/interop/openmm/__init__.py
- openff/interchange/smirnoff/_gromacs.py
> Error if HMR results in negative particle mass

- .github/workflows/beta.yaml
- .github/workflows/ci.yaml
- .github/workflows/examples.yaml
> Switch CI to use `macos-latest`

- .github/workflows/beta.yaml
- .github/workflows/ci.yaml
Reverts openforcefield/openff-interchange#1108
> Revert "Bump codecov/codecov-action from 4 to 5"

- docs/annotations.md
- docs/index.md
- docs/releasehistory.md
- openff/interchange/_annotations.py
- openff/interchange/_tests/unit_tests/test_annotations.py
Ref https://github.com/openforcefield/status/issues/96
https://openff-docs--1105.org.readthedocs.build/projects/interchange/en/1105/annotations.html
> Document Pydantic/Pint helpers

- docs/releasehistory.md
> Finalize 0.4.1 release notes

- openff/interchange/_tests/unit_tests/interop/gromacs/export/test_export.py
- openff/interchange/interop/gromacs/_import/_import.py
- openff/interchange/interop/gromacs/_import/combine.py
> Read GROMACS topology files split into `.itp` files

- docs/using/edges.md
Punts on whether or not #1075 is consistent with the ethos of SMIRNOFF and just documents _that_ it happens
> Document sharp edge of charges and `Interchange.combine`

- docs/releasehistory.md
- openff/interchange/_tests/unit_tests/interop/gromacs/test_interchange.py
- openff/interchange/interop/gromacs/_import/_import.py
- openff/interchange/interop/gromacs/_import/_topology.py
- openff/interchange/interop/gromacs/_interchange.py
- openff/interchange/interop/gromacs/export/_export.py
- openff/interchange/interop/gromacs/models/models.py
- openff/interchange/smirnoff/_gromacs.py
> Do not assume molecules are grouped

- docs/releasehistory.md
- openff/interchange/_tests/regression_tests/components/test_interchange.py
- openff/interchange/components/interchange.py
> Match toolkit behavior when writing PDB files

- examples/load-SAMPL6/README.md
- examples/load-SAMPL6/load-SAMPL6.ipynb
Needs #1186 to get acceptable results
> Add example loading and comparing energy evaluations of prepared SAMPL6 system

- docs/releasehistory.md
- docs/using/output.md
- openff/interchange/_tests/unit_tests/interop/lammps/export/test_lammps.py
- openff/interchange/_tests/unit_tests/interop/lammps/test_provenance.py
- openff/interchange/components/interchange.py
- openff/interchange/interop/lammps/export/export.py
- openff/interchange/interop/lammps/export/provenance.py
> Add (optional) type labels to LAMMPS export

- docs/releasehistory.md
- openff/interchange/components/interchange.py
- openff/interchange/interop/openmm/_import/_import.py
> Do not treat topology argument as optional

- docs/using/output.md
Closes #1237
I'm not sure how best to organize small details like this. I can comfortably defend myself against "it's not documented" but I cannot say this is particularly searchable. Tagging #1236
> Document how to control GROMACS molecule names

- openff/interchange/_tests/test_issues.py
- openff/interchange/components/potentials.py
This points to a larger issue in the models which warrants further testing; this fix, however, should be fairly straightforward.
Fixes #1209
> Fix JSON deserialization with preset charges

- openff/interchange/components/_packmol.py
> Fix `box_shape` docstring

- .github/workflows/beta.yaml
- .github/workflows/ci.yaml
- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/examples_env.yaml
Work around https://github.com/conda-forge/openff-nagl-feedstock/issues/45
> Bump OpenEye Toolkits to 2025 line

- docs/releasehistory.md
https://github.com/openforcefield/openff-interchange/milestone/23
> Finalize 0.4.5 release notes

- docs/conf.py
- openff/interchange/components/_packmol.py
- openff/interchange/components/interchange.py
- openff/interchange/components/mdconfig.py
- openff/interchange/components/toolkit.py
- openff/interchange/drivers/amber.py
- openff/interchange/drivers/gromacs.py
- openff/interchange/drivers/lammps.py
- openff/interchange/drivers/openmm.py
- openff/interchange/drivers/report.py
- openff/interchange/interop/_virtual_sites.py
- openff/interchange/interop/amber/export/_export.py
- openff/interchange/interop/gromacs/_interchange.py
- openff/interchange/interop/openmm/__init__.py
Resolves #1295
There are probably a few cases I've missed from the regex patterns I've grepped. But I think I got most of them
> Do not duplicate type annotations in docstrings

- .pre-commit-config.yaml
- examples/load-SAMPL6/load-SAMPL6.ipynb
- openff/interchange/_annotations.py
- openff/interchange/interop/gromacs/_interchange.py
- openff/interchange/interop/openmm/__init__.py
- openff/interchange/interop/openmm/_gbsa.py
- openff/interchange/smirnoff/_base.py
- openff/interchange/smirnoff/_nonbonded.py
- openff/interchange/smirnoff/_valence.py
- plugins/nonbonded_plugins/nonbonded.py
- pyproject.toml
> Declare minimum Python version

- docs/releasehistory.md
- openff/interchange/_tests/unit_tests/operations/test_combine.py
- openff/interchange/operations/_combine.py
> Fix key collisions in `Interchange.combine`

- .github/workflows/beta.yaml
- .pre-commit-config.yaml
- docs/releasehistory.md
- openff/interchange/_tests/unit_tests/operations/test_combine.py
- openff/interchange/components/interchange.py
- openff/interchange/operations/_combine.py
> FIx key collision over-correction

- devtools/conda-envs/dev_env.yaml
- devtools/conda-envs/docs_env.yaml
- devtools/conda-envs/examples_env.yaml
- devtools/conda-envs/test_env.yaml
- devtools/conda-envs/test_not_py313.yaml
> Do not use Pydantic 2.12 in tests
